Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-12, with the labels that each got.

#598 [유저] 모바일웹 사이드 내비바 UI 수정
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/pages/Auth/ModifyInfoPage/hooks/useUserInfoUpdate.ts
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/hooks/useNicknameCheckServer.ts
  src/static/category.ts
Labels: 🐞 BugFix, 👤 User

#603 [주변상점] 혜택 관련 ab 테스트 종료 및 결과 반영
  src/api/store/entity.ts
  src/assets/svg/benefit-icon.svg
  src/components/Store/BenefitRotator/BenefitRotator.module.scss
  src/components/Store/BenefitRotator/index.tsx
  src/pages/IndexPage/components/IndexStore/index.tsx
  src/pages/Store/StoreDetailPage/StoreDetailPage.module.scss
  src/pages/Store/StoreDetailPage/index.tsx
  src/pages/Store/StorePage/components/MobileStoreList/MobileStoreList.module.scss
  src/pages/Store/StorePage/components/MobileStoreList/index.tsx
Labels: ✨ Feature

#607 [유저] 개인정보처리방침 페이지 구현
  src/App.tsx
  src/components/common/Footer/index.tsx
  src/pages/PolicyPage/PolicyPage.module.scss
  src/pages/PolicyPage/index.tsx
  src/static/policy.ts
  src/static/routes.ts
Labels: 🖌 UI, 👤 User

#601 [시간표] 강의 수정 기능 추가
  .pnp.cjs
  .yarn/cache/@esbuild-darwin-arm64-npm-0.21.5-62349c1520-8.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.21.5-eddc2b5ad6-8.zip
  .yarn/cache/@rollup-rollup-darwin-arm64-npm-4.22.4-1dd8e67109-8.zip
  .yarn/cache/@rollup-rollup-win32-x64-msvc-npm-4.22.4-f32030f087-8.zip
  .yarn/cache/@types-lodash-npm-4.17.13-ec44e3530a-d0bf8fbd95.zip
  package.json
  src/api/timetable/entity.ts
  src/assets/svg/lecture-close-icon.svg
  src/assets/svg/lecture-edit-icon.svg
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/TimetablePage/MainTimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/index.tsx
  src/pages/TimetablePage/components/CustomLecture/CustomLecture.module.scss
  src/pages/TimetablePage/components/CustomLecture/index.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/Timetable/Timetable.module.scss
  src/pages/TimetablePage/components/Timetable/index.tsx
  src/pages/TimetablePage/hooks/useEditTimetableLecture.ts
  src/pages/TimetablePage/hooks/useMyLectures.ts
  src/pages/TimetablePage/hooks/useTimetableInfoList.ts
  src/pages/TimetablePage/hooks/useTimetableMutation.ts
  yarn.lock
Labels: ✨ Feature, 👤 User

#610 [유저] 회원가입 페이지 성별 선택 불가 이슈 해결
  src/pages/Auth/SignupPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#616 [hotfix, 시간표] 계절학기 시 강의 수정 페이지 안 들어가지는 오류 수정
  src/components/TimetablePage/LectureTable/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/index.tsx
  src/pages/TimetablePage/components/CustomLecture/index.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
Labels: 🐞 BugFix, 👤 User
