Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-04, with the labels that each got.

#144 [시간표] 강의 검색 시 학부 필터링 미작동하는 학부 수정
  src/components/TimetablePage/DefaultPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#154 [공통] 클라이언트 에러 처리
  src/global.d.ts
  src/pages/Auth/LoginPage/index.tsx
  src/utils/ts/sendClientError.ts
Labels: ⚙ Setting, 📬 API

#152 [GA] 전화번호 로깅 기능 추가 및 userID 쿠키 저장
  src/components/common/LogPage/index.tsx
  src/pages/Store/StoreDetailPage/index.tsx
Labels: 📊DA

#156 [식단] 메인 식단, 상세 식단 모바일 UI 변경 및 품절, 이미지 추가
  .gitignore
  src/assets/svg/close-icon.svg
  src/assets/svg/no_meals.svg
  src/assets/svg/no_photography.svg
  src/interfaces/Cafeteria.ts
  src/pages/Cafeteria/CafeteriaPage/CafeteriaPage.module.scss
  src/pages/Cafeteria/CafeteriaPage/components/WeeklyDatePicker/WeeklyDatePicker.module.scss
  src/pages/Cafeteria/CafeteriaPage/components/WeeklyDatePicker/hooks/usePickerCarousel.ts
  src/pages/Cafeteria/CafeteriaPage/components/WeeklyDatePicker/index.tsx
  src/pages/Cafeteria/CafeteriaPage/index.tsx
  src/pages/IndexPage/IndexPage.module.scss
  src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
Labels: ✨ Feature, 🎓 Campus

#151 [시간표] 모바일웹 시간표 페이지 작성
  src/components/TimetablePage/DefaultPage/index.tsx
  src/components/TimetablePage/Listbox/Listbox.module.scss
  src/components/TimetablePage/MobilePage/MobilePage.module.scss
  src/components/TimetablePage/MobilePage/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/components/TimetablePage/hooks/useAddTimetableLecture.ts
  src/components/TimetablePage/hooks/useDeleteTimetableLecture.ts
  src/components/TimetablePage/hooks/useDeptList.ts
  src/components/TimetablePage/hooks/useLectureList.ts
  src/components/TimetablePage/hooks/useSelect.ts
  src/components/TimetablePage/hooks/useSemester.ts
  src/components/TimetablePage/hooks/useTimetableInfoList.ts
  src/components/TimetablePage/hooks/useVersionInfo.ts
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/TimetablePage.module.scss
  src/pages/TimetablePage/index.tsx
Labels: ✨ Feature, 👤 User

#160 [유저] Recoil 마이그레이션
  .eslintrc.json
  .pnp.cjs
  .yarn/cache/use-sync-external-store-npm-1.2.0-44f75d2564-5c639e0f8d.zip
  .yarn/cache/zustand-npm-4.5.2-4f034a2f1c-160052a7fa.zip
  package.json
  src/components/common/Header/Header.module.scss
  src/components/common/Header/index.tsx
  src/pages/Auth/LoginPage/index.tsx
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/utils/hooks/useLogout.ts
  src/utils/hooks/useTokenState.ts
  src/utils/hooks/useUser.ts
  src/utils/hooks/useUserInfo.ts
  src/utils/zustand/index.ts
  yarn.lock
Labels: 👤 User

#161 Feature/#138/상점 상세페이지 이벤트 확인 기능
  src/api/store/APIDetail.ts
  src/api/store/entity.ts
  src/api/store/index.ts
  src/assets/svg/hidden-info-arrow.svg
  src/assets/svg/see-info-arrow.svg
  src/assets/svg/update-icon.svg
  src/components/common/UpdateInfo/UpdateInfo.module.scss
  src/components/common/UpdateInfo/UpdateInfo.tsx
  src/pages/Store/StoreDetailPage/EventTable/EventTable.module.scss
  src/pages/Store/StoreDetailPage/EventTable/components/EventCard.module.scss
  src/pages/Store/StoreDetailPage/EventTable/components/index.tsx
  src/pages/Store/StoreDetailPage/EventTable/hooks/useStoreEventList.ts
  src/pages/Store/StoreDetailPage/EventTable/index.tsx
  src/pages/Store/StoreDetailPage/index.tsx
Labels: ✨ Feature

#163 [모바일 사이드바] 문의하기, 사장님 진입점 추가
  src/components/common/Header/Header.module.scss
  src/components/common/Header/index.tsx
  src/static/category.ts
Labels: 👤 User

#168 [시간표] 시간표 스타일 수정
  src/components/TimetablePage/DefaultPage/index.tsx
  src/components/TimetablePage/MobilePage/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/static/timetable.ts
  src/utils/recoil/semester.ts
Labels: ❗QA issue, 👤 User

#171 [시간표] 강의 시간 잘못 표시되는 이슈 해결
  src/utils/hooks/useTimetableDayList.ts
Labels: 🐞 BugFix, 👤 User

#174 [시간표] 시간표 이미지 저장 화질 개선
  .pnp.cjs
  .yarn/cache/@types-dom-to-image-npm-2.6.7-f696a34e70-aecdd8bb06.zip
  .yarn/cache/@types-file-saver-npm-2.0.7-39f33a4b39-c3d1cd80ea.zip
  .yarn/cache/base64-arraybuffer-npm-1.0.2-18f4899892-15e6400d2d.zip
  .yarn/cache/css-line-break-npm-2.1.0-a1fd810d69-37b1fe632b.zip
  .yarn/cache/dom-to-image-npm-2.6.0-8af9792314-0d1f450b77.zip
  .yarn/cache/file-saver-npm-2.0.5-2c3bc40d53-c62d96e5ce.zip
  .yarn/cache/html2canvas-npm-1.4.1-fa13983145-c134324af5.zip
  .yarn/cache/text-segmentation-npm-1.0.3-634201c349-2e24632d59.zip
  .yarn/cache/utrie-npm-1.0.2-909cbd985c-c96fbb7d4d.zip
  package.json
  src/components/TimetablePage/DefaultPage/index.tsx
  src/components/TimetablePage/MobilePage/index.tsx
  src/components/TimetablePage/Timetable/index.tsx
  src/utils/hooks/useImageDownload.ts
  yarn.lock
Labels: ❗QA issue, 👤 User

#183 [유저 로그인] 무효화 된 accessToken 처리
  src/pages/Auth/LoginPage/index.tsx
  src/utils/recoil/index.ts
  src/utils/ts/cookie.ts
Labels: 🐞 BugFix

#185 [식단] 식단 카드 클릭 이벤트 범위 확장
  src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
Labels: ❗QA issue, 🎓 Campus

#201 [식당] 웹, 모바일 컴포넌트 분리 리팩토링
  src/App.tsx
  src/interfaces/Cafeteria.ts
  src/pages/Cafeteria/Cafeteria.module.scss
  src/pages/Cafeteria/CafeteriaPage/CafeteriaPage.module.scss
  src/pages/Cafeteria/CafeteriaPage/components/MenuBlock/index.tsx
  src/pages/Cafeteria/CafeteriaPage/components/WeeklyDatePicker/index.tsx
  src/pages/Cafeteria/CafeteriaPage/hooks/useCafeteriaList.ts
  src/pages/Cafeteria/CafeteriaPage/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/MobileMenuBlock.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/WeeklyDatePicker.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/hooks/usePickerCarousel.ts
  src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
  src/pages/Cafeteria/hooks/useCafeteriaList.ts
  src/pages/Cafeteria/index.tsx
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
  src/static/cafeteria.ts
Labels: 🔨 Refactor

#206 [식단, 버스, 커뮤니티] 캠퍼스팀 로깅 작업
  src/components/Post/HotPost/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Header/index.tsx
  src/pages/BusPage/BusLookUp/index.tsx
  src/pages/BusPage/BusTimetable/Timetable.tsx
  src/pages/BusPage/BusTimetable/index.tsx
  src/pages/IndexPage/components/IndexBus/index.tsx
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
  src/pages/IndexPage/components/IndexNotice/index.tsx
Labels: 🎓 Campus, 📊DA

#213 [비즈니스] 비즈니스팀 로깅 작업
  src/components/common/Header/index.tsx
  src/pages/IndexPage/components/IndexStore/index.tsx
  src/pages/Store/StoreDetailPage/index.tsx
  src/pages/Store/StorePage/index.tsx
Labels: 💼 Business

#211 [유저] 유저팀 로그 추가
  src/components/common/Header/index.tsx
  src/pages/Auth/LoginPage/index.tsx
  src/pages/Auth/SignupPage/index.tsx
Labels: 👤 User
