Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-08, with the labels that each got.

#392 [캠퍼스] QA 이슈 수정
  src/components/Cafeteria/CafeteriaInfo/CafeteriaInfo.module.scss
  src/components/Cafeteria/CafeteriaInfo/index.tsx
  src/components/common/Header/MobileHeader/index.tsx
  src/pages/Auth/LoginPage/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx
  src/pages/IndexPage/IndexPage.module.scss
  src/pages/IndexPage/index.tsx
  src/utils/hooks/auth/useLoginRedirect.ts
  src/utils/hooks/layout/useResetHeaderButton.ts
  src/utils/ts/apiClient.ts
  src/utils/ts/auth.ts
  src/utils/zustand/headerButtonStore.ts
Labels: ❗QA issue, 🎓 Campus

#391 feat: 시간표 강의 정보 api 연결
  src/api/timetable/APIDetail.ts
  src/api/timetable/entity.ts
  src/api/timetable/index.ts
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/components/CustomLecture/index.tsx
  src/pages/Timetable/hooks/useTimetableV2InfoList.ts
Labels: 📬 API, 👤 User

#393 [캠퍼스] QA 이슈 수정(버스)
  src/pages/BusPage/BusTimetable/BusTimetable.module.scss
  src/pages/BusPage/BusTimetable/Timetable.tsx
  src/pages/IndexPage/components/IndexBus/IndexBus.module.scss
  src/pages/IndexPage/components/IndexBus/index.tsx
Labels: ❗QA issue

#394 [business][Review] 상점 리스트 페이지 별점 리뷰 표기 UI 변경 및 검색 로직 수정
  .pnp.cjs
  .yarn/cache/@bcsdlab-utils-npm-0.0.12-85afb79bdf-ebcfc783e7.zip
  .yarn/cache/@bcsdlab-utils-npm-0.0.15-dd5b1007f1-4fc9c8bdb3.zip
  .yarn/cache/@types-josa-npm-3.0.5-a7b1759723-33680d6f4e.zip
  .yarn/cache/jongseong-npm-0.4.2-59df5ce5d2-e3904d8644.zip
  .yarn/cache/josa-npm-3.0.1-29853dc8f4-0930d8a1bc.zip
  package.json
  src/api/store/APIDetail.ts
  src/api/store/entity.ts
  src/api/store/index.ts
  src/assets/svg/mobile-store-search-icon.svg
  src/pages/Store/StorePage/StorePage.module.scss
  src/pages/Store/StorePage/components/DesktopStoreList/DesktopStoreList.module.scss
  src/pages/Store/StorePage/components/DesktopStoreList/index.tsx
  src/pages/Store/StorePage/components/MobileStoreList/MobileStoreList.module.scss
  src/pages/Store/StorePage/components/MobileStoreList/index.tsx
  src/pages/Store/StorePage/components/SearchBar/SearchBar.module.scss
  src/pages/Store/StorePage/components/SearchBar/index.tsx
  src/pages/Store/StorePage/index.tsx
  src/utils/ts/apiClient.ts
  src/utils/ts/qsStringfy.ts
  yarn.lock
Labels: ✨ Feature, 💼 Business

#400 [캠퍼스] QA 이슈 해결
  src/assets/svg/bubble-tail-bottom.svg
  src/components/Cafeteria/CafeteriaInfo/CafeteriaInfo.module.scss
  src/components/Cafeteria/CafeteriaInfo/index.tsx
  src/components/common/Header/MobileHeader/index.tsx
  src/pages/Auth/LoginPage/index.tsx
  src/pages/BusPage/BusTimetable/BusTimetable.module.scss
  src/pages/BusPage/BusTimetable/Timetable.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/PCDiningBlocks.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
  src/pages/Cafeteria/hooks/useDatePicker.ts
  src/pages/IndexPage/IndexPage.module.scss
  src/pages/IndexPage/components/IndexBus/IndexBus.module.scss
  src/pages/IndexPage/components/IndexBus/index.tsx
  src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
  src/pages/IndexPage/index.tsx
  src/utils/hooks/auth/useLoginRedirect.ts
  src/utils/hooks/layout/useResetHeaderButton.ts
  src/utils/ts/apiClient.ts
  src/utils/ts/auth.ts
  src/utils/ts/cafeteria.ts
  src/utils/zustand/headerButtonStore.ts
Labels: ❗QA issue, 🎓 Campus

#405 [캠퍼스] 누락된 로깅 추가
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/pages/IndexPage/components/IndexBus/index.tsx
Labels: 🎓 Campus, 📊DA

#402 [주변상점] 리뷰 신고하기 기능 추가
  src/App.tsx
  src/api/store/APIDetail.ts
  src/api/store/entity.ts
  src/api/store/index.ts
  src/assets/svg/Review/report-item-checked.svg
  src/assets/svg/Review/report-item-circle.svg
  src/components/common/CommonCheckBox/CheckBox.module.scss
  src/components/common/CommonCheckBox/index.tsx
  src/index.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/ReviewReporting.module.scss
  src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/components/ReportingLabel/ReportingLabel.module.scss
  src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/components/ReportingLabel/index.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/index.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewReporting/query/useReviewReport.ts
  src/pages/Store/StoreDetailPage/Review/components/SelectButton/SelectButton.module.scss
  src/pages/Store/StoreDetailPage/Review/components/SelectButton/SelectButton.tsx
  src/static/category.ts
Labels: 📬 API, ✨ Feature, 🖌 UI

#399 [비즈니스] 리뷰 삭제 기능 추가
  src/api/store/APIDetail.ts
  src/api/store/entity.ts
  src/api/store/index.ts
  src/assets/svg/Review/phone.svg
  src/assets/svg/pen-icon.svg
  src/assets/svg/trash-can-icon.svg
  src/assets/svg/up-arrow-icon.svg
  src/components/common/KoinToast/index.module.scss
  src/components/common/KoinToast/index.tsx
  src/pages/Store/StoreDetailPage/Review/components/AverageRating/AverageRating.tsx
  src/pages/Store/StoreDetailPage/Review/components/DeleteModal/DeleteModal.module.scss
  src/pages/Store/StoreDetailPage/Review/components/DeleteModal/DeleteModal.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewButton/index.module.scss
  src/pages/Store/StoreDetailPage/Review/components/ReviewButton/index.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewCard/ReviewCard.module.scss
  src/pages/Store/StoreDetailPage/Review/components/ReviewCard/ReviewCard.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewList/ReviewList.module.scss
  src/pages/Store/StoreDetailPage/Review/components/ReviewList/ReviewList.tsx
  src/pages/Store/StoreDetailPage/Review/components/SelectButton/SelectButton.module.scss
  src/pages/Store/StoreDetailPage/Review/components/SelectButton/SelectButton.tsx
  src/pages/Store/StoreDetailPage/Review/index.module.scss
  src/pages/Store/StoreDetailPage/Review/index.tsx
  src/pages/Store/StoreDetailPage/StoreDetailPage.module.scss
  src/pages/Store/StoreDetailPage/hooks/useDeleteReview.ts
  src/pages/Store/StoreDetailPage/hooks/useGetMyReview.ts
  src/pages/Store/StoreDetailPage/hooks/useGetReview.ts
  src/pages/Store/StoreDetailPage/index.tsx
  src/utils/hooks/koinToast/useKoinToast.tsx
Labels: ✨ Feature

#410 [식단] 인덱스 페이지 식단 글자 깨짐
  src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
Labels: 🐞 BugFix

#407 [시간표] 학기 추가/삭제 기능
  src/assets/svg/trash-can-icon.svg
  src/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/Timetable/components/SemesterList/AddSemesterModal/AddSemesterModal.module.scss
  src/pages/Timetable/components/SemesterList/AddSemesterModal/index.tsx
  src/pages/Timetable/components/SemesterList/DeleteSemesterModal/DeleteSemesterModal.module.scss
  src/pages/Timetable/components/SemesterList/DeleteSemesterModal/index.tsx
  src/pages/Timetable/components/SemesterList/SemesterList.module.scss
  src/pages/Timetable/components/SemesterList/index.tsx
  src/pages/Timetable/hooks/useAddSemester.ts
  src/pages/Timetable/hooks/useDeleteSemester.ts
  src/pages/Timetable/hooks/useMySemester.ts
  src/pages/Timetable/hooks/useSemesterOptionList.ts
  src/pages/Timetable/hooks/useTimetableFrameList.ts
  src/utils/zustand/semester.ts
Labels: ✨ Feature, 👤 User

#372 [hotfix] access토큰 만료 시 페이지 이동 조건 추가
  src/utils/hooks/state/useTokenState.ts
  src/utils/ts/apiClient.ts
  src/utils/zustand/auth.ts
Labels: 🐞 BugFix, 👤 User

#416 [유저] 유저팀 로깅 추가
  src/components/TimetablePage/Listbox/index.tsx
  src/components/common/Footer/index.tsx
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/components/common/Header/MobileHeader/index.tsx
  src/components/common/Header/PCHeader/index.tsx
  src/pages/Auth/LoginPage/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/components/Curriculum.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/SemesterListbox.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
  src/utils/hooks/analytics/useLogger.ts
Labels: 👤 User, 📊DA

#415 [캠퍼스] 캠퍼스팀 모바일 로깅 추가
  src/pages/IndexPage/components/IndexBus/index.tsx
Labels: 🎓 Campus, 📊DA

#412 [비즈니스] 리뷰하기 QA 반영
  src/pages/StoreReviewPage/ReviewForm/ReviewForm.module.scss
  src/pages/StoreReviewPage/ReviewForm/ReviewForm.tsx
Labels: ❗QA issue, 💼 Business

#406 [식단] 좋아요 로그인 유도 모달
  src/api/notice/APIDetail.ts
  src/components/Cafeteria/CafeteriaInfo/index.tsx
  src/components/Cafeteria/LoginPromptModal/LoginPromptModal.module.scss
  src/components/Cafeteria/LoginPromptModal/index.tsx
  src/components/Post/PostDetailHeader/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/DetailImage/DetailImage.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/DetailImage/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/MobileDiningBlocks.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/DetailModal/DetailModal.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/DetailModal/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/LoginPromptModal/LoginPromptModal.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/LoginPromptModal/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
  src/pages/Notice/NoticeDetailPage/index.tsx
  src/utils/hooks/ui/useBodyScrollLock.ts
Labels: ✨ Feature, 🎓 Campus

#419 [시간표] 유저팀 QA 반영
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/utils/zustand/myTempLecture.ts
Labels: ❗QA issue, 👤 User

#432 [핫픽스] api path 변경 배포 대응
  src/api/notice/APIDetail.ts
  src/components/Post/PostDetailHeader/index.tsx
  src/pages/Notice/NoticeDetailPage/index.tsx
Labels: 📬 API

#426 [유저] 유저팀 로깅 수정, 공통 로그 수정
  src/components/TimetablePage/Listbox/index.tsx
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/components/common/Header/MobileHeader/index.tsx
  src/pages/TimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/components/Curriculum.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
  src/pages/TimetablePage/index.tsx
  src/utils/hooks/analytics/useLogger.ts
Labels: 👤 User, 📊DA

#433 [유저] api v2 연결 및 프레임 기능 수정
  src/App.tsx
  src/api/timetable/APIDetail.ts
  src/api/timetable/entity.ts
  src/api/timetable/index.ts
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Timetable/index.tsx
  src/interfaces/Lecture.ts
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/ModifyTimetablePage/index.tsx
  src/pages/Timetable/TimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/TimetablePage/MobilePage/index.tsx
  src/pages/Timetable/TimetablePage/index.tsx
  src/pages/Timetable/components/CustomLecture/index.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/DownloadTimetableModal/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/pages/Timetable/components/TimetableList/index.tsx
  src/pages/Timetable/components/TotalGrades/index.tsx
  src/pages/Timetable/hooks/useAddTimetableLectureV2.ts
  src/pages/Timetable/hooks/useDeleteTimetableLectureV2.ts
  src/pages/Timetable/hooks/useMyLectures.ts
  src/pages/Timetable/hooks/useMyLecturesV2.ts
  src/pages/Timetable/hooks/useTimetableV2InfoList.ts
  src/pages/Timetable/hooks/useTimetableV2Mutation.ts
  src/utils/hooks/useTimetableDayListV2.ts
  src/utils/zustand/myLecturesV2.ts
  src/utils/zustand/myTempLectureV2.ts
Labels: 🐞 BugFix, 📬 API, 👤 User

#435 [공지사항] 공지사항 api 변경사항 적용 및 리팩토링
  src/api/coopshop/APIDetail.ts
  src/api/notice/APIDetail.ts
  src/api/notice/entity.ts
  src/api/notice/index.ts
  src/components/Post/HotPost/index.tsx
  src/components/Post/PostDetailContent/index.tsx
  src/components/Post/PostHeader/index.tsx
  src/components/Post/PostList/index.tsx
  src/components/common/LoadingSpinner/index.tsx
  src/pages/IndexPage/components/IndexNotice/index.tsx
  src/pages/Notice/NoticeDetailPage/NoticeDetailPage.module.scss
  src/pages/Notice/NoticeDetailPage/hooks/useArticleDetail.ts
  src/pages/Notice/NoticeDetailPage/index.tsx
  src/pages/Notice/NoticeListPage/NoticeListPage.module.scss
  src/pages/Notice/NoticeListPage/hooks/useArticleList.ts
  src/pages/Notice/NoticeListPage/index.tsx
  src/pages/Notice/NoticePage/NoticePage.module.scss
  src/pages/Notice/NoticePage/hooks/useHotArticle.tsx
  src/pages/Notice/NoticePage/index.tsx
  src/pages/Notice/components/ArticleContent/ArticleContent.module.scss
  src/pages/Notice/components/ArticleContent/index.tsx
  src/pages/Notice/components/ArticleHeader/ArticleHeader.module.scss
  src/pages/Notice/components/ArticleHeader/index.tsx
  src/pages/Notice/components/HotArticle/HotArticles.module.scss
  src/pages/Notice/components/HotArticle/index.tsx
  src/pages/Notice/components/NoticeHeader/NoticeHeader.module.scss
  src/pages/Notice/components/NoticeHeader/index.tsx
  src/pages/Notice/components/NoticeList/NoticeList.module.scss
  src/pages/Notice/components/NoticeList/index.tsx
  src/pages/Notice/components/Pagination/Pagination.module.scss
  src/pages/Notice/components/Pagination/index.tsx
  src/pages/Notice/hooks/useArticle.ts
  src/pages/Notice/hooks/useArticles.ts
  src/pages/Notice/hooks/useHotArticle.ts
  src/pages/Notice/hooks/usePageParams.ts
  src/pages/Notice/hooks/usePagination.ts
  src/utils/ts/setArticleCreateDate.ts
Labels: 📬 API, 🔨 Refactor

#439 [캠퍼스] 식단 로깅 구체화
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
Labels: 🎓 Campus, 📊DA

#441 [캠퍼스] 로깅 버그 수정
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
Labels: 🎓 Campus, 📊DA

#434 [시간표] 나의 강의 목록
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/common/ToggleButton/ToggleButton.module.scss
  src/components/common/ToggleButton/index.tsx
  src/pages/Timetable/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/Timetable/components/LectureList/LastUpdatedDate.tsx
  src/pages/Timetable/components/LectureList/LectureList.module.scss
  src/pages/Timetable/components/LectureList/index.tsx
  src/utils/hooks/useTimetableDayListV2.ts
Labels: ✨ Feature, 👤 User

#444 [비즈니스] 신고하기 변경된 플로우 반영
  src/api/store/entity.ts
  src/pages/Store/StoreDetailPage/Review/components/ReviewCard/ReviewCard.module.scss
  src/pages/Store/StoreDetailPage/Review/components/ReviewCard/ReviewCard.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewList/ReviewList.tsx
  src/pages/Store/StoreDetailPage/Review/components/SelectButton/SelectButton.tsx
Labels: ❗QA issue, 💼 Business

#442 [시간표] 비로그인자 시간표 일부 기능 제한
  src/api/timetable/entity.ts
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/TimetablePage/index.tsx
  src/pages/Timetable/components/CustomLecture/CustomLecture.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureDefaultInput/CustomLectureDefaultInput.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureTimeInput/CustomLectureTimeInput.module.scss
  src/pages/Timetable/components/CustomLecture/index.tsx
  src/pages/Timetable/components/InducingLoginModal/InducingLoginModal.module.scss
  src/pages/Timetable/components/InducingLoginModal/index.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/pages/Timetable/components/SemesterList/AddSemesterModal/index.tsx
  src/pages/Timetable/components/SemesterList/index.tsx
  src/pages/Timetable/components/TimetableList/TimetableSettingModal/index.tsx
  src/pages/Timetable/components/TimetableList/index.tsx
  src/pages/Timetable/hooks/useDeleteSemester.ts
  src/pages/Timetable/hooks/useMyLecturesV2.ts
  src/pages/Timetable/hooks/useTimetableFrameList.ts
  src/pages/Timetable/hooks/useTimetableV2Mutation.ts
  src/pages/Timetable/hooks/useUpdateTimetableFrame.ts
  src/utils/zustand/myLecturesV2.ts
Labels: 🐞 BugFix, 👤 User

#446 [캠퍼스] 캠퍼스팀 로깅 수정
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/pages/BusPage/BusTimetable/Timetable.tsx
Labels: 🎓 Campus, 📊DA

#449 [유저] 유저팀 로깅 수정
  src/components/common/Header/PCHeader/index.tsx
  src/utils/hooks/data/useTimetableDayList.ts
Labels: 👤 User, 📊DA

#452 [공지사항] 공지사항 페이징 버그 수정 (hotfix)
  src/api/notice/entity.ts
  src/components/Post/Pagination/index.tsx
  src/pages/Notice/NoticeListPage/index.tsx
Labels: 🐞 BugFix, 🎓 Campus

#453 [시간표] V2 쿼리키 수정
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Timetable/index.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/DownloadTimetableModal/index.tsx
  src/pages/Timetable/hooks/useAddTimetableLecture.ts
  src/pages/Timetable/hooks/useAddTimetableLectureV2.ts
  src/pages/Timetable/hooks/useDeleteTimetableLecture.ts
  src/pages/Timetable/hooks/useDeleteTimetableLectureV2.ts
  src/pages/Timetable/hooks/useMyLectures.ts
  src/pages/Timetable/hooks/useTimetableInfoList.ts
  src/pages/Timetable/hooks/useTimetableMutation.ts
  src/pages/Timetable/hooks/useTimetableV2InfoList.ts
  src/pages/Timetable/hooks/useTimetableV2Mutation.ts
  src/utils/zustand/myLectures.ts
Labels: 🐞 BugFix, 👤 User

#457 [비즈니스] 로깅 에러 수정
  src/components/common/Header/MobileHeader/index.tsx
  src/components/common/Header/PCHeader/index.tsx
  src/pages/IndexPage/components/IndexStore/index.tsx
  src/pages/Store/StoreDetailPage/index.tsx
  src/pages/Store/StorePage/components/DesktopStoreList/index.tsx
  src/pages/Store/StorePage/components/MobileStoreList/index.tsx
Labels: 🐞 BugFix, 💼 Business

#461 [비즈니스] 리뷰 필터버튼이 on 될때만 로깅되도록 수정
  src/pages/Store/StorePage/index.tsx
  src/utils/hooks/analytics/useLogger.ts
Labels: 🐞 BugFix, 💼 Business

#465 [공지사항] api 수정 적용
  src/api/notice/APIDetail.ts
  src/api/notice/entity.ts
  src/pages/IndexPage/components/IndexNotice/index.tsx
  src/pages/Notice/NoticeDetailPage/index.tsx
  src/pages/Notice/components/ArticleHeader/ArticleHeader.module.scss
  src/pages/Notice/components/ArticleHeader/index.tsx
  src/pages/Notice/components/NoticeList/NoticeList.module.scss
  src/pages/Notice/components/NoticeList/index.tsx
  src/utils/ts/setArticleCreateDate.ts
  src/utils/ts/setArticleRegisteredDate.ts
Labels: 📬 API

#462 [시간표] 아직 존재하지 않는 학기 에러 핸들링
  src/pages/Timetable/hooks/useAddSemester.ts
Labels: 🐞 BugFix, 👤 User
