Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-03, with the labels that each got.

#77 [식단 페이지] 모바일 환경에서 식단 더보기 이벤트 추가
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
Labels: bug

#95 [#84]메뉴 정보 변경일 추가
  src/api/store/entity.ts
  src/components/common/UpdateInfo/UpdateInfo.module.scss
  src/components/common/UpdateInfo/UpdateInfo.tsx
  src/pages/Store/StoreDetailPage/StoreDetailPage.module.scss
  src/pages/Store/StoreDetailPage/index.tsx
Labels: ✨ Feature

#97 [#96] 주변 상점 가기 링크 수정
  src/static/category.ts
Labels: 🐞 BugFix, 💼 Business

#89 [#81] 시간표 마지막 업데이트 날짜 보여주기 기능 추가
  src/api/timetable/APIDetail.ts
  src/api/timetable/entity.ts
  src/api/timetable/index.ts
  src/components/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/components/TimetablePage/DefaultPage/hooks/useVersionInfo.ts
  src/components/TimetablePage/DefaultPage/index.tsx
  src/pages/IndexPage/components/IndexTimetable/IndexTimetable.module.scss
  src/pages/IndexPage/components/IndexTimetable/index.tsx
Labels: ✨ Feature, 👤 User

#115 [버스] 버스 남은 분 계산 로직 수정
  src/pages/BusPage/ts/busModules.ts
Labels: 🐞 BugFix, 🎓 Campus

#117 [시간표] 메인 페이지의 시간표에서 같은 강의 시간 표시 삭제
  src/pages/IndexPage/components/IndexTimetable/index.tsx
Labels: 🐞 BugFix, 👤 User

#119 [편의] 병합 시 삐봇 서버에 요청 추가
  .github/workflows/CHECK_PR_MERGED.yml
  .github/workflows/PICK_REVIEWER.yml
Labels: ⚙ Setting

#112 [유저] 유저 정보변경 페이지 이슈 및 문구 수정
  src/components/common/Header/Header.module.scss
  src/components/common/Header/index.tsx
  src/pages/Auth/LoginPage/index.tsx
  src/pages/Auth/ModifyInfoPage/components/UserDeleteModal/UserDeleteModal.module.scss
  src/pages/Auth/ModifyInfoPage/components/UserDeleteModal/index.tsx
  src/pages/Auth/ModifyInfoPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#129 [시간표] 시간표 auto focus 제거, cursor pointer 추가, table css 수정
  src/components/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/Timetable/Timetable.module.scss
Labels: 🐞 BugFix, 👤 User

#132 [공통] 기능 메인페이지 scroll to top 적용
  src/pages/BusPage/index.tsx
  src/pages/Cafeteria/CafeteriaPage/index.tsx
  src/pages/Notice/NoticePage/index.tsx
  src/pages/Room/RoomPage/index.tsx
  src/pages/Store/StorePage/index.tsx
  src/pages/TimetablePage/index.tsx
Labels: 🐞 BugFix, 👤 User

#133 [시간표] 메인페이지 의 시간표 수정
  src/components/TimetablePage/DefaultPage/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
Labels: 🐞 BugFix, 👤 User

#137 [시간표] 나의 시간표 화면 넘어가는 이슈 해결
  src/components/TimetablePage/DefaultPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#120 [시간표] 강의 검색 학부 필터링 적용
  src/components/TimetablePage/DefaultPage/index.tsx
Labels: ✨ Feature, 👤 User
