Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-11, with the labels that each got.

#569 [식단] 식단 좋아요 삭제
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
Labels: 🔨 Refactor

#566 [시간표] 콘솔 에러 해결
  src/components/TimetablePage/LectureTable/index.tsx
  src/pages/TimetablePage/components/Curriculum/index.tsx
  src/pages/TimetablePage/components/CustomLecture/index.tsx
  src/pages/TimetablePage/components/InducingLoginModal/index.tsx
  src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/DownloadTimetableModal.module.scss
  src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/index.tsx
  src/pages/TimetablePage/components/SemesterList/AddSemesterModal/index.tsx
  src/pages/TimetablePage/components/Timetable/index.tsx
Labels: 🐞 BugFix, 👤 User

#567 [유저] 회원가입 및 정보수정 페이지 UI 수정
  src/assets/svg/chervron-up-down.svg
  src/assets/svg/chervron-up.svg
  src/components/TimetablePage/Listbox/Listbox.module.scss
  src/components/TimetablePage/Listbox/NewListbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/SignupPage.module.scss
  src/pages/Auth/SignupPage/index.tsx
  src/pages/Store/StoreDetailPage/Review/components/ReviewList/ReviewList.tsx
Labels: 👤 User

#573 [hotfix, 시간표] 장소에 쉼표 입력 방지
  src/pages/TimetablePage/components/CustomLecture/index.tsx
Labels: 🐞 BugFix, 👤 User

#576 [비즈니스] 리뷰하기 툴팁 기능 추가
  src/api/store/APIDetail.ts
  src/assets/svg/close-icon-20x20.svg
  src/pages/IndexPage/components/IndexStore/index.tsx
  src/pages/Store/StorePage/StorePage.module.scss
  src/pages/Store/StorePage/index.tsx
Labels: 💼 Business

#570 [비즈니스] 이벤트 배너 개편
  src/pages/Store/StorePage/components/EventCarousel/EventCarousel.module.scss
  src/pages/Store/StorePage/components/EventCarousel/hooks/useCarouselController.ts
  src/pages/Store/StorePage/components/EventCarousel/index.tsx
Labels: 💼 Business

#580 [시간표] 강의 추가 api 요청값 수정
  src/api/timetable/entity.ts
  src/components/Cafeteria/CafeteriaInfo/index.tsx
  src/pages/TimetablePage/hooks/useTimetableV2Mutation.ts
Labels: 📬 API, 👤 User

#591 [시간표] 시간표 이미지 저장 에러 수정
  src/pages/TimetablePage/components/MainTimetable/index.tsx
Labels: 👤 User

#589 [유저] 학부를 선택해도 반영되지 않는 이슈
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#594 [주변상점] 모바일 툴팁 오류 수정
  src/components/common/IntroToolTip/index.tsx
  src/pages/Store/StorePage/index.tsx
Labels: 🐞 BugFix

#595 [시간표] 강의 추가/수정 api 요청 및 응답값 수정
  src/api/timetable/APIDetail.ts
  src/api/timetable/entity.ts
  src/api/timetable/index.ts
  src/components/TimetablePage/LectureTable/index.tsx
  src/interfaces/Lecture.ts
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/MainTimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/components/CustomLecture/index.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/index.tsx
  src/pages/TimetablePage/components/MainTimetable/index.tsx
  src/pages/TimetablePage/components/Timetable/index.tsx
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
  src/pages/TimetablePage/components/TotalGrades/index.tsx
  src/pages/TimetablePage/hooks/useAddTimetableLecture.ts
  src/pages/TimetablePage/hooks/useDeleteTimetableFrame.ts
  src/pages/TimetablePage/hooks/useDeleteTimetableLecture.ts
  src/pages/TimetablePage/hooks/useMyLectures.ts
  src/pages/TimetablePage/hooks/useTimetableDayList.ts
  src/pages/TimetablePage/hooks/useTimetableDayListV2.ts
  src/pages/TimetablePage/hooks/useTimetableInfoList.ts
  src/pages/TimetablePage/hooks/useTimetableMutation.ts
  src/pages/TimetablePage/hooks/useTimetableV2InfoList.ts
  src/pages/TimetablePage/hooks/useUpdateTimetableFrame.ts
  src/utils/zustand/myCustomTempLecture.ts
  src/utils/zustand/myLectures.ts
  src/utils/zustand/myTempLecture.ts
Labels: 🔨 Refactor, 👤 User
