Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-09, with the labels that each got.

#458 [시간표] 로그인시 시간표 에러 수정
  src/pages/IndexPage/components/IndexNotice/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/Timetable/hooks/useTimetableFrameList.ts
Labels: 🐞 BugFix, 👤 User

#456 [시간표] 커스텀 시간표 기능
  src/api/timetable/entity.ts
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/components/common/Toast/TimetableToast/index.tsx
  src/components/common/Toast/useToast.tsx
  src/interfaces/Lecture.ts
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/components/CustomLecture/CustomLecture.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureDefaultInput/CustomLectureDefaultInput.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureDefaultInput/index.tsx
  src/pages/Timetable/components/CustomLecture/CustomLectureLocationTimeSetting/index.tsx
  src/pages/Timetable/components/CustomLecture/CustomLectureTimeInput/CustomLectureTimeInput.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureTimeInput/index.tsx
  src/pages/Timetable/components/CustomLecture/index.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/TimetableList/TimetableSettingModal/index.tsx
  src/pages/Timetable/hooks/useDeleteSemester.ts
  src/pages/Timetable/hooks/useTimetableV2Mutation.ts
  src/static/timetable.ts
  src/utils/hooks/useTimetableDayListV2.ts
  src/utils/zustand/myCustomTempLecture.ts
Labels: ✨ Feature, 👤 User

#477 [유저] 유저팀 로그 복구
  .eslintrc.json
  src/components/TimetablePage/Listbox/index.tsx
  src/components/TimetablePage/Timetable/index.tsx
  src/components/common/CommonCheckBox/index.tsx
  src/components/common/KoinToast/index.tsx
  src/components/common/LoginRequiredModal/index.tsx
  src/components/common/MetaHelmet/index.tsx
  src/components/common/Toast/TimetableToast/index.tsx
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/MainTimetablePage/index.tsx
  src/pages/TimetablePage/components/Curriculum.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
  src/pages/TimetablePage/components/SemesterList/index.tsx
Labels: 👤 User, 📊DA

#482 [시간표] 버튼 디자인 수정 및 메인 학기 지정 에러 수정
  src/assets/svg/download-icon.svg
  src/assets/svg/pen-icon.svg
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/MyLectureTimetable.module.scss
  src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/TimetableSettingModal.module.scss
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
Labels: 🐞 BugFix, 👤 User

#488 [시간표] 불필요한 코드 삭제 및 변수명 수정
  .vscode/settings.json
  src/assets/svg/timetable-icon.svg
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/MainTimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/MainTimetablePage/MobilePage/MobilePage.module.scss
  src/pages/TimetablePage/MainTimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/components/Curriculum/Curriculum.module.scss
  src/pages/TimetablePage/components/Curriculum/index.tsx
  src/pages/TimetablePage/components/LectureList/LectureList.module.scss
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/DownloadTimetableModal.module.scss
  src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/index.tsx
  src/pages/TimetablePage/components/MainTimetable/MyLectureTimetable.module.scss
  src/pages/TimetablePage/components/MainTimetable/index.tsx
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
  src/pages/TimetablePage/components/SemesterList/index.tsx
  src/pages/TimetablePage/components/Timetable/Timetable.module.scss
  src/pages/TimetablePage/components/Timetable/index.tsx
  src/pages/TimetablePage/components/TimetableHeader/TimetableHeader.module.scss
  src/pages/TimetablePage/components/TimetableHeader/index.tsx
  src/pages/TimetablePage/components/TimetableList/index.tsx
Labels: 👤 User

#483 [시간표] 드롭다운 잘림 해소
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/MainTimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/components/Curriculum/index.tsx
  src/pages/TimetablePage/components/CustomLecture/CustomLecture.module.scss
  src/pages/TimetablePage/components/CustomLecture/index.tsx
  src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/index.tsx
  src/pages/TimetablePage/components/MainTimetable/index.tsx
  src/pages/TimetablePage/components/SemesterList/index.tsx
  src/pages/TimetablePage/components/Timetable/index.tsx
  src/pages/TimetablePage/hooks/useTimetableDayListV2.ts
  src/utils/hooks/useOnClickOutside.ts
Labels: 🐞 BugFix, 👤 User

#490 [시간표] 시간표 추가시 해당 시간표로 이동하게 수정
  src/pages/TimetablePage/MainTimetablePage/index.tsx
  src/pages/TimetablePage/components/MainTimetable/MyLectureTimetable.module.scss
  src/pages/TimetablePage/components/TimetableList/index.tsx
Labels: 👤 User

#492 [시간표] 학기 삭제 시 모달 생성과 함께 화면 움직임
  src/components/common/Modal/AlertModal/index.tsx
Labels: 🐞 BugFix, 👤 User

#500 [핫픽스] 공지사항 날짜 형식 문제
  src/utils/ts/setArticleRegisteredDate.ts
Labels: 🐞 BugFix

#499 [시간표] 시간표 추가시 프레임 이동 수정
  src/pages/TimetablePage/MainTimetablePage/index.tsx
  src/pages/TimetablePage/components/TimetableList/index.tsx
  src/pages/TimetablePage/hooks/useAddSemester.ts
  src/pages/TimetablePage/hooks/useDeleteSemester.ts
Labels: 🐞 BugFix, 👤 User

#509 [식단] 아침, 점심 식단 변경 시간 조정
  src/utils/ts/cafeteria.ts
Labels: 🐞 BugFix, 🔨 Refactor

#501 [시간표] lable로 영역 수정
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/TimetableSettingModal.module.scss
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
Labels: ❗QA issue

#503 [시간표] 비로그인 시 중복 시간표 토스트에러 문구 수정
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/Timetable/index.tsx
Labels: ❗QA issue

#514 [시간표] 커스텀 일정 저장 전 경고 메시지 안 뜨도록 수정
  src/api/timetable/APIDetail.ts
  src/pages/TimetablePage/components/CustomLecture/index.tsx
Labels: ❗QA issue, 👤 User

#516 [시간표] 시간표에 시간 잘못 나오는 이슈 해결
  src/pages/TimetablePage/hooks/useTimetableDayListV2.ts
Labels: 🐞 BugFix, 👤 User

#513 [시간표] 메인 프레임 로직 수정 및 라벨 svg추가
  src/assets/svg/Review/check.svg
  src/assets/svg/book-mark.svg
  src/components/common/Modal/ImageModal/index.tsx
  src/pages/Auth/ModifyInfoPage/components/AuthenticateUserModal/index.tsx
  src/pages/Auth/ModifyInfoPage/components/UserDeleteModal/index.tsx
  src/pages/TimetablePage/components/SemesterList/DeleteSemesterModal/index.tsx
  src/pages/TimetablePage/components/TimetableList/TimetableList.module.scss
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/TimetableSettingModal.module.scss
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
  src/pages/TimetablePage/components/TimetableList/index.tsx
Labels: ❗QA issue

#510 [시간표] 삭제 되돌리기 기능
  src/api/timetable/entity.ts
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/common/Toast/TimetableToast/TimetableToast.module.scss
  src/components/common/Toast/TimetableToast/index.tsx
  src/pages/TimetablePage/components/Timetable/index.tsx
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
  src/pages/TimetablePage/components/TimetableList/index.tsx
  src/pages/TimetablePage/hooks/useDeleteSemester.ts
  src/pages/TimetablePage/hooks/useDeleteTimetableFrame.ts
  src/pages/TimetablePage/hooks/useTimetableV2Mutation.ts
Labels: ✨ Feature, 👤 User

#519 [시간표] 빈 강의 목록에 대한 문구 추가
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/LectureTable/index.tsx
  src/pages/TimetablePage/components/LectureList/LectureList.module.scss
  src/pages/TimetablePage/components/LectureList/index.tsx
Labels: 🖌 UI, 👤 User

#524 [hotfix] 회원 학과 정보 불러오기
  src/pages/Auth/ModifyInfoPage/index.tsx
Labels: 🐞 BugFix, 👤 User
