Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-10, with the labels that each got.

#526 [시간표] 시간 및 장소 삭제 기능 추가
  src/pages/TimetablePage/components/CustomLecture/CustomLecture.module.scss
  src/pages/TimetablePage/components/CustomLecture/index.tsx
Labels: ❗QA issue, 👤 User

#531 [시간표] 학기 삭제 api 연동
  src/api/timetable/APIDetail.ts
  src/api/timetable/entity.ts
  src/api/timetable/index.ts
  src/pages/TimetablePage/hooks/useDeleteSemester.ts
Labels: 📬 API, 👤 User

#532 [시간표] 학기 없을 시 문구 추가 및 버튼 disable 처리
  src/pages/TimetablePage/components/MainTimetable/index.tsx
  src/pages/TimetablePage/components/SemesterList/index.tsx
  src/pages/TimetablePage/components/TimetableList/TimetableList.module.scss
  src/pages/TimetablePage/components/TimetableList/index.tsx
Labels: ❗QA issue, 👤 User

#534 [hotfix] 학기 설정 오류 수정
  src/pages/TimetablePage/components/SemesterList/index.tsx
Labels: 👤 User

#536 [상점] 생협 운영 시간 추가
  src/App.tsx
  src/api/coopshop/APIDetail.ts
  src/api/coopshop/entity.ts
  src/api/coopshop/index.ts
  src/components/Cafeteria/CafeteriaInfo/index.tsx
  src/pages/CampusInfo/CampusInfo.module.scss
  src/pages/CampusInfo/hooks/useCampusInfo.ts
  src/pages/CampusInfo/index.tsx
  src/pages/CampusInfo/svg/book.svg
  src/pages/CampusInfo/svg/cafe.svg
  src/pages/CampusInfo/svg/cut.svg
  src/pages/CampusInfo/svg/flatware.svg
  src/pages/CampusInfo/svg/laundry.svg
  src/pages/CampusInfo/svg/post-office.svg
  src/pages/CampusInfo/svg/print.svg
  src/static/routes.ts
Labels: ✨ Feature

#538 [hotfix, 시간표] 학기 관련 이슈
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/components/MainTimetable/index.tsx
  src/pages/TimetablePage/components/SemesterList/index.tsx
  src/pages/TimetablePage/components/TimetableList/TimetableSettingModal/index.tsx
Labels: 🐞 BugFix, 👤 User

#541 [유저] 유저팀 리뷰어 수정
  .github/workflows/reviewer.json
Labels: ⚙ Setting, 👤 User

#539 [시간표] UI 수정
  src/components/common/Toast/TimetableToast/TimetableToast.module.scss
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/TimetablePage/components/SemesterList/AddSemesterModal/AddSemesterModal.module.scss
  src/pages/TimetablePage/components/SemesterList/DeleteSemesterModal/DeleteSemesterModal.module.scss
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
Labels: 🖌 UI, 👤 User

#545 [공지사항] QA 이슈 수정
  src/api/notice/APIDetail.ts
  src/pages/IndexPage/components/IndexNotice/index.tsx
  src/pages/Notice/components/Pagination/index.tsx
Labels: ❗QA issue, 🎓 Campus

#557 [시간표] 학기 추가하기 버튼 스타일 수정
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
  src/pages/TimetablePage/components/SemesterList/index.tsx
Labels: 👤 User

#560 [캠퍼스] 교내 시설물 정보 로깅 추가
  src/components/common/Footer/index.tsx
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/components/common/Header/PCHeader/index.tsx
Labels: 🎓 Campus

#558 [공통] 404페이지 추가
  src/App.tsx
  src/assets/svg/page-not-found-error.svg
  src/pages/Error/PageNotFound/PageNotFound.module.scss
  src/pages/Error/PageNotFound/index.tsx
  src/static/routes.ts
Labels: ✨ Feature

#562 [hotfix] 정보수정에서 닉네임이 필수값이 되어버리는 이슈
  src/pages/Auth/ModifyInfoPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#565 [비즈니스] 카테고리 추가에 따른 UI 대응
  src/pages/IndexPage/components/IndexStore/IndexStore.module.scss
  src/pages/IndexPage/components/IndexStore/index.tsx
  src/pages/Store/StorePage/StorePage.module.scss
  src/pages/Store/StorePage/index.tsx
Labels: 🐞 BugFix
