Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-06, with the labels that each got.

#307 [식단] 식단 이미지 조건문 변경 등 리팩토링
  src/api/cafeteria/APIDetail.ts
  src/api/cafeteria/entity.ts
  src/api/cafeteria/index.ts
  src/assets/svg/chevron-left.svg
  src/assets/svg/chevron-right.svg
  src/assets/svg/no-photography-mobile.svg
  src/assets/svg/no-photography-pc.svg
  src/assets/svg/not-served.svg
  src/interfaces/Cafeteria.ts
  src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/MobileDiningBlocks.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMealImage/MobileMealImage.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMealImage/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/DetailModal/DetailModal.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/DetailModal/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/PCDiningBlocks.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMealImage/PCMealImage.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMealImage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/PCMenuBlocks.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
  src/pages/Cafeteria/hooks/useCafeteriaList.ts
  src/pages/Cafeteria/hooks/useDinings.ts
  src/pages/Cafeteria/hooks/usePickerCarousel.ts
  src/pages/Cafeteria/index.tsx
  src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
  src/static/cafeteria.ts
  src/utils/ts/cafeteria.ts
Labels: 🔨 Refactor, 🎓 Campus

#306 [시간표] 시간표 메인페이지 구현
  src/assets/svg/add-icon.svg
  src/assets/svg/checked-icon.svg
  src/assets/svg/curriculum-icon.svg
  src/assets/svg/download-icon.svg
  src/assets/svg/edit-icon.svg
  src/assets/svg/not-checked-icon.svg
  src/assets/svg/setting-icon.svg
  src/components/TimetablePage/Listbox/NewListbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/Timetable/TimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/TimetablePage/MobilePage/index.tsx
  src/pages/Timetable/components/Curriculum.tsx
  src/pages/Timetable/components/LectureList/LectureList.module.scss
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/pages/Timetable/components/SemesterList/SemesterList.module.scss
  src/pages/Timetable/components/SemesterList/SemesterSettingModal/SemesterSettingModal.module.scss
  src/pages/Timetable/components/SemesterList/SemesterSettingModal/index.tsx
  src/pages/Timetable/components/SemesterList/index.tsx
  src/pages/Timetable/components/SemesterListbox.tsx
  src/pages/Timetable/components/TimetableList.tsx
  src/pages/Timetable/components/TimetableList/TimetableList.module.scss
  src/pages/Timetable/components/TimetableList/TimetableSettingModal/TimetableSettingModal.module.scss
  src/pages/Timetable/components/TimetableList/TimetableSettingModal/index.tsx
  src/pages/Timetable/components/TimetableList/index.tsx
Labels: 🖌 UI, 👤 User

#311 [시간표] 시간표 내 강의 UI 개선
  src/assets/svg/edit-icon.svg
  src/assets/svg/not-checked-icon.svg
  src/assets/svg/pen-icon.svg
  src/components/TimetablePage/Listbox/NewListbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/Timetable/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/Timetable/components/LectureList/DeptListbox.tsx
  src/pages/Timetable/components/LectureList/LastUpdatedDate.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/LectureTimetable.tsx
  src/pages/Timetable/components/MyLectureTimetable/MyLectureTimetable.module.scss
  src/pages/Timetable/components/MyLectureTimetable/TotalGrades.tsx
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/pages/Timetable/components/SemesterList/index.tsx
  src/pages/Timetable/components/TimetableList/TimetableList.module.scss
  src/pages/Timetable/components/TimetableList/index.tsx
  src/static/timetable.ts
Labels: 🖌 UI, 👤 User

#313 [시간표] 커스텀 시간표 삭제 기능 추가
  src/assets/svg/lecture-close-icon.svg
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/components/common/Modal/AlertModal/AlertModal.module.scss
  src/components/common/Modal/AlertModal/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/MyLectureTimetable.module.scss
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/pages/Timetable/components/TotalGrades/TotalGrades.module.scss
  src/pages/Timetable/components/TotalGrades/index.tsx
Labels: 👤 User

#315 fix: 정규식 맨 끝 g 플래그 삭제하여 에러 수정
  src/pages/Auth/SignupPage/index.tsx
Labels: 👤 User

#317 [식단] 학식당 운영시간 조회 추가 등 UI 변경사항
  src/App.tsx
  src/assets/svg/close-icon-grey.svg
  src/assets/svg/information.svg
  src/components/Post/Pagination/index.tsx
  src/components/Post/PostList/index.tsx
  src/components/Room/RoomDetailImg/index.tsx
  src/components/Room/RoomDetailMap/index.tsx
  src/components/Room/RoomDetailOption/index.tsx
  src/components/Room/RoomDetailTable/index.tsx
  src/components/Room/RoomList/index.tsx
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/components/common/Header/MobileHeader/index.tsx
  src/components/common/Header/PCHeader/index.tsx
  src/components/common/Modal/PortalProvider.tsx
  src/index.scss
  src/pages/BusPage/BusLookUp/index.tsx
  src/pages/BusPage/hooks/useBusLeftTime.ts
  src/pages/Cafeteria/Cafeteria.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMealImage/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/CafeteriaInfo/CafeteriaInfo.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/CafeteriaInfo/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/DateNavigator.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/DetailModal/DetailModal.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/DetailModal/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/PCDiningBlocks.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMealImage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
  src/pages/IndexPage/components/IndexBus/index.tsx
  src/pages/Room/RoomDetailPage/hooks/useDetailMarker.ts
  src/pages/Timetable/components/Curriculum.tsx
  src/pages/Timetable/components/SemesterList/SemesterSettingModal/index.tsx
  src/static/cafeteria.ts
  src/utils/zustand/mobileSidebar.ts
Labels: 🔨 Refactor, 🖌 UI, 🎓 Campus

#321 [유저] 회원가입 시 이메일 전체를 적는 경우 에러 분기 처리
  src/pages/Auth/SignupPage/index.tsx
Labels: 👤 User

#320 [유저] 정규 시간표 더블클릭 이벤트, 알림 메시지 수정
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/common/LogPage/index.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/utils/recoil/userInfoState.ts
Labels: 👤 User

#323 [시간표] 시간표 늘리기
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/static/timetable.ts
Labels: ✨ Feature, 👤 User

#325 [시간표] 직접 추가 UI 구현
  .vscode/settings.json
  src/components/TimetablePage/Listbox/NewListbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/components/CustomLecture/CustomLecture.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureDefaultInput/CustomLectureDefaultInput.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureDefaultInput/index.tsx
  src/pages/Timetable/components/CustomLecture/CustomLectureLocationTimeSetting/index.tsx
  src/pages/Timetable/components/CustomLecture/CustomLectureTimeInput/CustomLectureTimeInput.module.scss
  src/pages/Timetable/components/CustomLecture/CustomLectureTimeInput/index.tsx
  src/pages/Timetable/components/CustomLecture/index.tsx
  src/static/timetable.ts
Labels: 🖌 UI, 👤 User
