Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-05, with the labels that each got.

#214 [식단] 웹 식단 뷰 리뉴얼(MZ식단표)
  src/assets/svg/left-angle-bracket.svg
  src/assets/svg/lower-angle-bracket.svg
  src/assets/svg/modal-close-icon.svg
  src/assets/svg/no-meals-mobile.svg
  src/assets/svg/no-meals-pc.svg
  src/assets/svg/no-photography-mobile.svg
  src/assets/svg/no-photography-pc.svg
  src/assets/svg/right-angle-bracket.svg
  src/assets/svg/upper-angle-bracket.svg
  src/interfaces/Cafeteria.ts
  src/pages/Cafeteria/Cafeteria.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/DateNavigator.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/PCMenuBlocks.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
  src/pages/Cafeteria/hooks/useDatePicker.ts
  src/pages/Cafeteria/index.tsx
  src/static/cafeteria.ts
  src/utils/ts/cafeteria.ts
Labels: ✨ Feature

#226 [식단] 식단 웹뷰 문제 해결
  src/pages/Cafeteria/Cafeteria.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/PCMenuBlocks.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
Labels: 🔨 Refactor

#234 [식단] 식단 상세보기 사진 비율 조정
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/PCMenuBlocks.module.scss
Labels: ❗QA issue

#230 [유저] 유저팀 QA 이슈 및 기능 추가
  src/components/TimetablePage/Listbox/Listbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/components/common/Header/index.tsx
  src/pages/Auth/AuthPage/Auth.module.scss
  src/pages/Auth/AuthPage/index.tsx
  src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/SignupPage.module.scss
  src/pages/Auth/SignupPage/index.tsx
  src/pages/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/TimetablePage/DefaultPage/index.tsx
  src/static/dept.ts
Labels: 🐞 BugFix, 👤 User

#232 [시간표] 시간표 상태관리 마이그레이션 (recoil -> zustand)
  src/api/timetable/APIDetail.ts
  src/pages/Auth/LoginPage/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/LectureTimetable.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/SemesterListbox.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
  src/pages/TimetablePage/hooks/useDeleteTimetableLecture.ts
  src/pages/TimetablePage/hooks/useMyLectures.ts
  src/pages/TimetablePage/hooks/useSelect.ts
  src/pages/TimetablePage/hooks/useTimetableMutation.ts
  src/utils/hooks/useLogout.ts
  src/utils/hooks/useTokenState.ts
  src/utils/hooks/useUser.ts
  src/utils/recoil/index.ts
  src/utils/recoil/semester.ts
  src/utils/zustand/auth.ts
  src/utils/zustand/myLectures.ts
  src/utils/zustand/myTempLecture.ts
  src/utils/zustand/semester.ts
Labels: 🔨 Refactor, 👤 User

#238 [주변상점] 이벤트 기본 이미지 오류 및 내용 오류 수정
  .pnp.cjs
  .yarn/cache/dom-serializer-npm-2.0.0-378ebc7200-cd1810544f.zip
  .yarn/cache/domhandler-npm-5.0.3-3ede73dc10-0f58f4a6af.zip
  .yarn/cache/domutils-npm-3.1.0-66c92ef7eb-e5757456dd.zip
  .yarn/cache/entities-npm-4.5.0-7cdb83b832-853f8ebd5b.zip
  .yarn/cache/html-dom-parser-npm-5.0.8-6f09317bfc-f264d58665.zip
  .yarn/cache/html-react-parser-npm-5.1.10-887458c19c-b304921bd0.zip
  .yarn/cache/htmlparser2-npm-9.1.0-5ef8394060-e5f8d51939.zip
  .yarn/cache/inline-style-parser-npm-0.2.3-b8a7023d7a-ed6454de80.zip
  .yarn/cache/react-property-npm-2.0.2-55c6f95f6b-c67fb2590d.zip
  .yarn/cache/style-to-js-npm-1.1.12-55adf1b7c2-8c66706981.zip
  .yarn/cache/style-to-object-npm-1.0.6-b50013e448-5b58295dcc.zip
  package.json
  src/pages/Store/StoreDetailPage/EventTable/EventTable.module.scss
  src/pages/Store/StoreDetailPage/EventTable/components/EventCard/EventCard.module.scss
  src/pages/Store/StoreDetailPage/EventTable/components/EventCard/EventContent/EventContent.module.scss
  src/pages/Store/StoreDetailPage/EventTable/components/EventCard/EventContent/index.tsx
  src/pages/Store/StoreDetailPage/EventTable/components/EventCard/index.tsx
  src/pages/Store/StoreDetailPage/EventTable/index.tsx
  yarn.lock
Labels: 🐞 BugFix, 💼 Business

#243 [유저] 시간표 로깅 추가
  src/components/TimetablePage/DefaultPage/index.tsx
  src/components/TimetablePage/Listbox/index.tsx
  src/components/common/Header/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
Labels: 👤 User, 📊DA

#249 [시간표] 시간표 2차 스프린트 이슈 해결 (강의 정보, 타임테이블)
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
Labels: ❗QA issue, 👤 User

#251 [유저] 빌드 실패 해결
  src/pages/Auth/ModifyInfoPage/components/AuthenticateUserModal/AuthenticateUserModal.module.scss
Labels: 🐞 BugFix

#252 [시간표]시간표 이미지 하단 여백 제거
  src/pages/TimetablePage/MobilePage/MobilePage.module.scss
  src/pages/TimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/components/MyLectureTimetable/index.tsx
Labels: 🐞 BugFix, ❗QA issue

#256 [유저] 유저 QA 이슈 해결
  src/components/TimetablePage/Listbox/Listbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/hooks/useSignup.ts
  src/pages/Auth/SignupPage/index.tsx
  src/utils/ts/apiClient.ts
Labels: 🐞 BugFix, 👤 User

#262 [식단] 아이폰 기본폰트 색상 이슈 대응
  src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/WeeklyDatePicker.module.scss
Labels: 🐞 BugFix, ❗QA issue

#270 [공통] iOS 폰트색상 전역적으로 수정
  src/index.scss
Labels: ❗QA issue

#272 [공통] iOS 기본 폰트 색상 수정
  src/index.scss
Labels: ❗QA issue

#275 [식단] 모바일 상세페이지 뒤로가기 오류 수정
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
Labels: 🐞 BugFix

#277 [식단] 주의 문구 추가
  src/pages/Cafeteria/Cafeteria.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/MobileMenuBlock.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
Labels: ❗QA issue

#281 [공통] 자동번역 삭제
  public/index.html
Labels: 🐞 BugFix

#290 [주변상점] 동일키 참조 문제 해결
  src/api/store/entity.ts
  src/pages/Store/StorePage/components/EventCarousel/index.tsx
Labels: 🐞 BugFix

#300 [상점] 로그 에러 수정
  src/pages/Store/StoreDetailPage/index.tsx
  src/pages/Store/StorePage/index.tsx
Labels: 🐞 BugFix

#299 [시간표] 정규 시간표 페이지
  src/App.tsx
  src/assets/svg/down-arrow-icon.svg
  src/assets/svg/pen-icon.svg
  src/assets/svg/timetable-icon.svg
  src/assets/svg/trash-can-icon.svg
  src/assets/svg/up-arrow-icon.svg
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Listbox/NewListbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/ModifyTimetablePage/ModifyTimetablePage.module.scss
  src/pages/Timetable/ModifyTimetablePage/index.tsx
  src/pages/Timetable/TimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/components/LectureList/DeptListbox .tsx
  src/pages/Timetable/components/LectureList/LastUpdatedDate.tsx
  src/pages/Timetable/components/LectureList/LectureList.module.scss
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/pages/Timetable/components/TimetableHeader/TimetableHeader.module.scss
  src/pages/Timetable/components/TimetableHeader/index.tsx
Labels: 🖌 UI, 👤 User

#291 [공통] 사이드 네비게이션 리뉴얼
  src/assets/svg/black-arrow-back-icon.svg
  src/assets/svg/hamburger-icon.svg
  src/assets/svg/koin-service-logo.svg
  src/assets/svg/person.svg
  src/assets/svg/white-arrow-back-icon.svg
  src/components/common/Footer/index.tsx
  src/components/common/Header/Header.module.scss
  src/components/common/Header/MobileHeader/MobileHeader.module.scss
  src/components/common/Header/MobileHeader/Panel/Panel.module.scss
  src/components/common/Header/MobileHeader/Panel/index.tsx
  src/components/common/Header/MobileHeader/index.tsx
  src/components/common/Header/PCHeader/PCHeader.module.scss
  src/components/common/Header/PCHeader/index.tsx
  src/components/common/Header/index.tsx
  src/pages/Auth/ModifyInfoPage/components/AuthenticateUserModal/index.tsx
  src/static/category.ts
  src/utils/hooks/useLogout.ts
  src/utils/zustand/mobileSidebar.ts
Labels: 🖌 UI

#301 [식단] 아침 식단 사진 삭제
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileMenuBlock/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCMenuBlocks/index.tsx
Labels: 🎓 Campus

#302 [유저] 회원가입 UI 수정
  src/components/TimetablePage/Listbox/Listbox.module.scss
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/SignupPage.module.scss
  src/pages/Auth/SignupPage/index.tsx
Labels: 👤 User
