Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2024-07, with the labels that each got.

#332 [시간표] 시간표 이미지 저장 모달 구현
  src/components/TimetablePage/Timetable/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/DownloadTimetableModal/DownloadTimetableModal.module.scss
  src/pages/Timetable/components/MyLectureTimetable/DownloadTimetableModal/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/static/timetable.ts
  src/utils/zustand/myLectures.ts
Labels: 🖌 UI, 👤 User

#336 [시간표] 시간표 미리보기 UI 개선
  src/components/TimetablePage/LectureTable/LectureTable.module.scss
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Timetable/Timetable.module.scss
  src/components/TimetablePage/Timetable/index.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/Timetable/TimetablePage/MobilePage/index.tsx
  src/pages/Timetable/components/LectureList/index.tsx
  src/pages/Timetable/components/MyLectureTimetable/index.tsx
  src/utils/zustand/myTempLecture.ts
Labels: 🖌 UI, 👤 User

#343 [시간표] 시간표 공통 토스트
  src/components/common/Toast/TimetableToast/TimetableToast.module.scss
  src/components/common/Toast/TimetableToast/index.tsx
  src/components/common/Toast/useToast.tsx
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
  src/utils/hooks/useToastTimer.ts
Labels: 👤 User

#346 [시간표] 시간표 저장 버튼 기능 수정
  src/pages/Timetable/ModifyTimetablePage/DefaultPage/index.tsx
Labels: 🐞 BugFix

#350 [hotfix] 시간표 동일한 과목 추가
  src/pages/TimetablePage/components/LectureList/index.tsx
Labels: 🐞 BugFix, 👤 User

#358 [유저] 디자인 수정
  src/api/timetable/entity.ts
  src/components/TimetablePage/Listbox/NewListbox.module.scss
  src/pages/Timetable/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/Timetable/components/Curriculum.tsx
  src/pages/Timetable/components/LectureList/LectureList.module.scss
  src/pages/Timetable/components/SemesterList/SemesterList.module.scss
  src/pages/Timetable/components/SemesterList/index.tsx
Labels: 👤 User

#361 [hotfix] 시간표 강의 시간 변경 안내문구 추가
  src/assets/svg/fixes-image.jpg
  src/pages/TimetablePage/DefaultPage/DefaultPage.module.scss
  src/pages/TimetablePage/DefaultPage/index.tsx
Labels: 👤 User

#363 [hotfix] 메인페이지로 돌아가지 않는 에러 수정
  src/pages/Auth/AuthPage/index.tsx
Labels: 🐞 BugFix

#364 [식단] 식단 주기 변경 및 툴팁 추가
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/components/WeeklyDatePicker/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/DateNavigator/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
  src/pages/Cafeteria/hooks/useDatePicker.ts
  src/pages/Cafeteria/index.tsx
  src/pages/IndexPage/IndexPage.module.scss
  src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
  src/utils/ts/cafeteria.ts
Labels: 🔨 Refactor, ✨ Feature, 🎓 Campus

#367 [버스] 버스카드 UI 리뉴얼 및 리다이렉트
  src/assets/svg/reverse-destination.svg
  src/pages/BusPage/BusTimetable/index.tsx
  src/pages/IndexPage/components/IndexBus/IndexBus.module.scss
  src/pages/IndexPage/components/IndexBus/index.tsx
  src/static/bus.ts
  src/utils/zustand/bus.ts
Labels: ✨ Feature

#382 [식단] 식단 좋아요 구현
  src/api/cafeteria/APIDetail.ts
  src/api/cafeteria/index.ts
  src/assets/svg/heart-filled.svg
  src/assets/svg/heart.svg
  src/interfaces/APIRequest.ts
  src/interfaces/Cafeteria.ts
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/MobileDiningBlocks.module.scss
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/PCDiningBlocks.module.scss
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
  src/pages/Cafeteria/hooks/useDinings.ts
  src/pages/IndexPage/components/IndexCafeteria/IndexCafeteria.module.scss
Labels: ✨ Feature, 🎓 Campus

#380 [시간표] 시간표 프레임 설정 기능 구현
  src/api/timetable/APIDetail.ts
  src/api/timetable/entity.ts
  src/api/timetable/index.ts
  src/assets/svg/setting-icon-blue.svg
  src/pages/Timetable/components/TimetableList/TimetableList.module.scss
  src/pages/Timetable/components/TimetableList/TimetableSettingModal/index.tsx
  src/pages/Timetable/components/TimetableList/index.tsx
  src/pages/Timetable/hooks/useAddTimetableFrame.ts
  src/pages/Timetable/hooks/useDeleteTimetableFrame.ts
  src/pages/Timetable/hooks/useMySemester.ts
  src/pages/Timetable/hooks/useSemesterOptionList.ts
  src/pages/Timetable/hooks/useTimetableFrameList.ts
  src/pages/Timetable/hooks/useUpdateTimetableFrame.ts
Labels: 📬 API, ✨ Feature, 👤 User
