Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2025-07, with the labels that each got.

#921 [유저] 정보수정 페이지 QA 이슈 해결
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/Steps/Terms/index.tsx
  src/static/terms.ts
Labels: 🐞 BugFix

#923 [hotfix] 모바일 웹 버그 수정
  src/components/layout/Header/MobileHeader/Panel/Panel.module.scss
  src/components/modal/Modal/ImageModal/ImageModal.module.scss
  src/components/modal/Modal/ImageModal/index.tsx
  src/utils/ts/touchHandler.ts
Labels: 🐞 BugFix

#944 [캠퍼스] 동아리 행사 생성 페이지 PC UI 구현
  src/App.tsx
  src/api/club/entity.ts
  src/pages/Club/NewClubEvent/NewClubEvent.module.scss
  src/pages/Club/NewClubEvent/components/ImagesUploadSlider/ImagesUploadSlider.module.scss
  src/pages/Club/NewClubEvent/components/ImagesUploadSlider/index.tsx
  src/pages/Club/NewClubEvent/components/TimeSelector/TimeSelector.module.scss
  src/pages/Club/NewClubEvent/components/TimeSelector/index.tsx
  src/pages/Club/NewClubEvent/hooks/useImageUpload.ts
  src/pages/Club/NewClubEvent/index.tsx
  src/static/routes.ts
Labels: 🖌 UI, 🎓 Campus

#960 [유저] 세션로깅 적용 및 정보수정 로깅 추가
  src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/index.tsx
  src/pages/Auth/SignupPage/Steps/MobileVerificationStep/index.tsx
  src/pages/Auth/SignupPage/Steps/StudentDetailStep/index.tsx
  src/pages/Auth/SignupPage/Steps/Terms/index.tsx
  src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx
  src/pages/Auth/SignupPage/index.tsx
  src/utils/hooks/auth/usePhoneVerification.ts
  src/utils/hooks/auth/useUserInfoUpdate.ts
Labels: 📊DA

#959 [캠퍼스] 행사 사진 슬라이드 구현 및 로깅 추가
  src/assets/svg/Club/next-image-icon.svg
  src/assets/svg/Club/pre-image-icon.svg
  src/pages/Club/ClubDetailPage/components/ClubEventCard/ClubEventCard.module.scss
  src/pages/Club/ClubDetailPage/components/ClubEventCard/index.tsx
  src/pages/Club/ClubDetailPage/components/ClubEventDetailView/ClubEventDetailView.module.scss
  src/pages/Club/ClubDetailPage/components/ClubEventDetailView/index.tsx
  src/pages/Club/ClubDetailPage/components/ClubEventList/index.tsx
  src/pages/Club/ClubDetailPage/components/ClubRecruitment/ClubRecruitment.module.scss
  src/pages/Club/ClubDetailPage/components/ClubRecruitment/index.tsx
  src/pages/Club/ClubDetailPage/index.tsx
Labels: ✨ Feature, 🖌 UI

#965 [캠퍼스] 동아리 PC뷰 모집&행사 삭제 수정 버튼 구현 및 검색기능 구현
  src/api/club/APIDetail.ts
  src/api/club/entity.ts
  src/api/club/index.ts
  src/pages/Club/ClubDetailPage/ClubDetailPage.module.scss
  src/pages/Club/ClubDetailPage/components/ClubEventDetailView/index.tsx
  src/pages/Club/ClubDetailPage/components/ClubRecruitment/index.tsx
  src/pages/Club/ClubDetailPage/hooks/useClubRecruitment.ts
  src/pages/Club/ClubDetailPage/index.tsx
  src/pages/Club/ClubEventEditPage/index.tsx
  src/pages/Club/ClubListPage/ClubListPage.module.scss
  src/pages/Club/ClubListPage/components/ClubSearchBar/ClubSearchBar.module.scss
  src/pages/Club/ClubListPage/components/ClubSearchBar/ClubSearchBar.tsx
  src/pages/Club/ClubListPage/components/ClubSearchBarModal/ClubSearchBarModal.module.scss
  src/pages/Club/ClubListPage/components/ClubSearchBarModal/ClubSearchBarModal.tsx
  src/pages/Club/ClubListPage/components/RelateSearchItem/RelateSearchItem.module.scss
  src/pages/Club/ClubListPage/components/RelateSearchItem/RelateSearchItem.tsx
  src/pages/Club/ClubListPage/index.tsx
  src/pages/Club/ClubRecruitmentEditPage/hooks/usePutClubRecruitment.ts
  src/pages/Club/ClubRecruitmentEditPage/index.tsx
  src/pages/Club/hooks/useClubList.ts
  src/static/routes.ts
Labels: ✨ Feature, 🎓 Campus
