Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2025-06, with the labels that each got.

#878 [캠퍼스] 동아리 상세 페이지 기능 누락 및 오류 수정
  src/assets/svg/Club/input-error-icon.svg
  src/pages/Club/ClubDetailPage/components/ClubQnA/index.tsx
  src/pages/Club/ClubDetailPage/index.tsx
  src/pages/Club/ClubListPage/index.tsx
  src/pages/Club/NewClubPage/components/MobileView/NewClubMobileView.module.scss
  src/pages/Club/NewClubPage/components/MobileView/index.tsx
  src/pages/Club/NewClubPage/components/PCView/NewClubPCView.module.scss
  src/pages/Club/NewClubPage/components/PCView/index.tsx
  src/pages/Club/components/ClubAuthModal/ClubAuthModal.module.scss
  src/pages/Club/components/ClubAuthModal/index.tsx
  src/pages/Club/components/ClubInputErrorCondition/ClubInputErrorCondition.module.scss
  src/pages/Club/components/ClubInputErrorCondition/index.tsx
Labels: 🐞 BugFix

#879 fix : 누락 로깅 추가
  src/pages/Club/ClubDetailPage/components/ClubQnA/index.tsx
  src/pages/Club/ClubDetailPage/components/ClubQnACard/index.tsx
  src/pages/Club/ClubDetailPage/components/CreateQnAModal/index.tsx
  src/pages/Club/ClubDetailPage/hooks/useClubManager.ts
  src/pages/Club/ClubDetailPage/index.tsx
  src/pages/Club/NewClubPage/components/AdditionalInfoModal/index.tsx
  src/pages/Club/NewClubPage/components/MobileView/index.tsx
  src/pages/Club/NewClubPage/components/PCView/index.tsx
Labels: 🐞 BugFix

#880 [유저] 유저 정보 변경 페이지 Desktop UI 변경 및 기능 추가
  src/App.tsx
  src/api/auth/APIDetail.ts
  src/api/auth/entity.ts
  src/api/auth/index.ts
  src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss
  src/pages/Auth/ModifyInfoPage/components/AuthenticateUserModal/AuthenticateUserModal.module.scss
  src/pages/Auth/ModifyInfoPage/components/AuthenticateUserModal/index.tsx
  src/pages/Auth/ModifyInfoPage/hooks/usePhoneVerification.ts
  src/pages/Auth/ModifyInfoPage/hooks/useValidationContext.tsx
  src/pages/Auth/ModifyInfoPage/hooks/useVerificationTimer.ts
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/utils/hooks/auth/useUserInfoUpdate.ts
  src/utils/ts/userTypeGuards.ts
Labels: ✨ Feature, 🖌 UI, 👤 User

#884 [유저] 정보 변경 모바일 UI 변경 및 기능 추가
  src/App.tsx
  src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss
  src/pages/Auth/ModifyInfoPage/hooks/useValidationContext.tsx
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/Steps/ExternalDetailStep/index.tsx
  src/pages/Auth/SignupPage/Steps/MobileExternalDetailStep/index.tsx
  src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/index.tsx
  src/pages/Auth/SignupPage/Steps/StudentDetailStep/index.tsx
Labels: 🖌 UI, 👤 User

#894 [캠퍼스] QA 이슈 해결
  src/api/club/APIDetail.ts
  src/components/ui/BannerB/BannerB.module.scss
  src/components/ui/BannerB/index.tsx
  src/pages/Club/ClubDetailPage/index.tsx
  src/pages/Club/ClubListPage/ClubListPage.module.scss
  src/pages/Club/ClubListPage/index.tsx
  src/pages/Club/components/ClubAuthModal/index.tsx
  src/pages/Club/hooks/useClubList.ts
  src/pages/IndexPage/components/IndexClub/ClubMobileViewB/ClubMobileViewB.module.scss
  src/pages/IndexPage/components/IndexClub/ClubMobileViewB/index.tsx
  src/pages/IndexPage/components/IndexClub/IndexClub.module.scss
  src/pages/IndexPage/components/IndexClub/index.tsx
  src/pages/IndexPage/index.tsx
Labels: ❗QA issue, 🎓 Campus

#896 [캠퍼스] 동아리 QA 수정
  src/api/auth/entity.ts
  src/api/club/entity.ts
  src/assets/svg/Club/copy-icon.svg
  src/assets/svg/Club/up-icon.svg
  src/components/layout/Footer/index.tsx
  src/components/layout/Header/MobileHeader/MobileHeader.module.scss
  src/components/layout/Header/MobileHeader/Panel/index.tsx
  src/components/layout/Header/MobileHeader/index.tsx
  src/components/layout/Header/PCHeader/index.tsx
  src/components/layout/Header/index.tsx
  src/pages/Club/ClubDetailPage/ClubDetailPage.module.scss
  src/pages/Club/ClubDetailPage/components/ClubIntrodution/ClubIntrodution.module.scss
  src/pages/Club/ClubDetailPage/components/ClubQnACard/ClubQnACard.module.scss
  src/pages/Club/ClubDetailPage/components/ClubQnACard/index.tsx
  src/pages/Club/ClubDetailPage/components/CreateQnAModal/CreateQnAModal.module.scss
  src/pages/Club/ClubDetailPage/components/MandateClubManagerModal/index.tsx
  src/pages/Club/ClubDetailPage/index.tsx
  src/pages/Club/ClubEditPage/conponents/EditConfirmModal/EditConfirmModal.module.scss
  src/pages/Club/ClubEditPage/conponents/EditConfirmModal/index.tsx
  src/pages/Club/ClubEditPage/index.tsx
  src/pages/Club/ClubListPage/index.tsx
  src/pages/Club/NewClubPage/components/AdditionalInfoModal/AdditionalInfoModal.module.scss
  src/pages/Club/NewClubPage/components/MobileView/NewClubMobileView.module.scss
  src/pages/Club/NewClubPage/components/MobileView/index.tsx
  src/pages/Club/NewClubPage/components/PCView/NewClubPCView.module.scss
  src/pages/Club/NewClubPage/components/PCView/index.tsx
  src/pages/Club/NewClubPage/hooks/usePostNewClub.ts
  src/pages/IndexPage/components/IndexClub/index.tsx
  src/utils/ts/formatPhoneNumber.ts
  src/utils/zustand/customTitle.ts
Labels: 🐞 BugFix

#910 fix: 모바일뷰 이미지 사이즈 조정
  src/pages/Club/ClubListPage/ClubListPage.module.scss
Labels: 🐞 BugFix

#909 [유저] 정보 변경 페이지 QA 수정
  src/App.tsx
  src/api/auth/entity.ts
  src/pages/Articles/LostItemChatPage/ProtectedLostItemChatPage.tsx
  src/pages/Articles/LostItemChatPage/index.tsx
  src/pages/Auth/ModifyInfoPage/ModifyInfoPage.module.scss
  src/pages/Auth/ModifyInfoPage/components/AuthenticateUserModal/index.tsx
  src/pages/Auth/ModifyInfoPage/hooks/usePhoneVerification.ts
  src/pages/Auth/ModifyInfoPage/hooks/useValidationContext.tsx
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/ModifyInfoPage/reducers/passwordReducer.ts
  src/utils/hooks/state/useUser.ts
Labels: 🐞 BugFix, ❗QA issue
