Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2025-04, with the labels that each got.

#797 [유저] 회원가입 페이지 이용약관 UI 추가
  src/assets/svg/check-icon.svg
  src/assets/svg/white-check-icon.svg
  src/pages/Auth/SignupPage/Steps/Terms/Terms.module.scss
  src/pages/Auth/SignupPage/Steps/Terms/index.tsx
  src/pages/Auth/SignupPage/components/CustomCheckbox/CustomCheckbox.module.scss
  src/pages/Auth/SignupPage/components/CustomCheckbox/index.tsx
  src/static/terms.ts
Labels: 🖌 UI, 👤 User

#803 [캠퍼스] 배너 모바일뷰 추가
  src/components/ui/Banner/Banner.module.scss
  src/components/ui/Banner/index.tsx
  src/components/ui/BannerB/BannerB.module.scss
  src/components/ui/BannerB/index.tsx
Labels: 🖌 UI, 🎓 Campus

#804 [캠퍼스] 메인 화면 배너 구현
  src/api/banner/APIDetail.ts
  src/api/banner/entity.ts
  src/api/banner/index.ts
  src/api/index.ts
  src/assets/svg/previous-arrow-icon.svg
  src/components/ui/Banner/Banner.module.scss
  src/components/ui/Banner/hooks/useBannerCategories.ts
  src/components/ui/Banner/hooks/useBanners.ts
  src/components/ui/Banner/index.tsx
  src/components/ui/BannerB/BannerB.module.scss
  src/components/ui/BannerB/index.tsx
  src/pages/IndexPage/index.tsx
  src/utils/hooks/analytics/useLogger.ts
Labels: ✨ Feature, 🎓 Campus

#806 [캠퍼스] 배너 QA 이슈 수정
  src/components/ui/Banner/Banner.module.scss
  src/components/ui/Banner/index.tsx
  src/components/ui/BannerB/BannerB.module.scss
  src/components/ui/BannerB/index.tsx
Labels: ❗QA issue, 🎓 Campus

#812 [캠퍼스] 배너 동작 추가
  .pnp.cjs
  .yarn/cache/react-swipeable-npm-7.0.2-351f02a9a7-3bcc470427.zip
  package.json
  src/components/ui/Banner/index.tsx
  src/components/ui/BannerB/index.tsx
  yarn.lock
Labels: ❗QA issue, 🎓 Campus

#815 [캠퍼스] 배너 로깅 값 수정
  src/components/ui/Banner/index.tsx
  src/components/ui/BannerB/index.tsx
Labels: 🐞 BugFix, 🎓 Campus

#817 [hotfix, 주변상점] 엔터 키 무한 입력으로 인한 무한 검색 이슈 해결
  src/pages/Store/StorePage/components/SearchBar/index.tsx
  src/pages/Store/StorePage/components/SearchBarModal/index.tsx
  src/pages/Store/StorePage/index.tsx
Labels: 🐞 BugFix, 💼 Business

#829 [배너] 화살표 및 슬라이드바 디자인 변경
  src/assets/svg/previous-arrow-icon.svg
  src/components/ui/Banner/Banner.module.scss
  src/components/ui/BannerB/BannerB.module.scss
Labels: 🖌 UI, 🎓 Campus

#830 [에러] develop push 에러
  .pnp.cjs
  .yarn/cache/react-hook-form-npm-7.55.0-a0b31dc513-ff37fba242.zip
  package.json
  src/App.tsx
  src/api/auth/APIDetail.ts
  src/api/auth/entity.ts
  src/api/auth/index.ts
  src/assets/svg/Login/chevron-left.svg
  src/assets/svg/Login/close.svg
  src/assets/svg/Login/correct.svg
  src/assets/svg/Login/error.svg
  src/assets/svg/Login/eye-close.svg
  src/assets/svg/Login/eye-open.svg
  src/assets/svg/Login/logo.svg
  src/assets/svg/Login/warning.svg
  src/assets/svg/face-icon.svg
  src/assets/svg/lock-icon.svg
  src/pages/Auth/AuthPage/Auth.module.scss
  src/pages/Auth/AuthPage/index.tsx
  src/pages/Auth/LoginPage/LoginPage.module.scss
  src/pages/Auth/LoginPage/components/AdditionalLink/AdditionalLink.module.scss
  src/pages/Auth/LoginPage/components/AdditionalLink/index.tsx
  src/pages/Auth/LoginPage/components/Footer/Footer.module.scss
  src/pages/Auth/LoginPage/components/Footer/index.tsx
  src/pages/Auth/LoginPage/components/LoginForm/LoginForm.module.scss
  src/pages/Auth/LoginPage/components/LoginForm/index.tsx
  src/pages/Auth/LoginPage/hooks/useLogin.ts
  src/pages/Auth/LoginPage/index.tsx
  src/pages/Auth/SignupPage/SignupPage.module.scss
  src/pages/Auth/SignupPage/Steps/CompleteStep/CompleteStep.module.scss
  src/pages/Auth/SignupPage/Steps/CompleteStep/index.tsx
  src/pages/Auth/SignupPage/Steps/MobileExternalDetailStep/MobileExternalDetailStep.module.scss
  src/pages/Auth/SignupPage/Steps/MobileExternalDetailStep/index.tsx
  src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/MobileStudentDetailStep.module.scss
  src/pages/Auth/SignupPage/Steps/MobileStudentDetailStep/index.tsx
  src/pages/Auth/SignupPage/Steps/MobileUserTypeStep/MobileUserTypeStep.module.scss
  src/pages/Auth/SignupPage/Steps/MobileUserTypeStep/index.tsx
  src/pages/Auth/SignupPage/Steps/MobileVerificationStep/MobileVerification.module.scss
  src/pages/Auth/SignupPage/Steps/MobileVerificationStep/index.tsx
  src/pages/Auth/SignupPage/Steps/Terms/Terms.module.scss
  src/pages/Auth/SignupPage/Steps/Terms/index.tsx
  src/pages/Auth/SignupPage/Steps/Verification/Verification.module.scss
  src/pages/Auth/SignupPage/Steps/Verification/index.tsx
  src/pages/Auth/SignupPage/components/CustomCheckbox/CustomCheckbox.module.scss
  src/pages/Auth/SignupPage/components/CustomCheckbox/index.tsx
  src/pages/Auth/SignupPage/components/CustomInput/CustomInput.module.scss
  src/pages/Auth/SignupPage/components/CustomInput/index.tsx
  src/pages/Auth/SignupPage/components/CustomSelector/CustomSelector.module.scss
  src/pages/Auth/SignupPage/components/CustomSelector/index.tsx
  src/pages/Auth/SignupPage/components/ProgressBar/ProgressBar.module.scss
  src/pages/Auth/SignupPage/components/ProgressBar/index.tsx
  src/pages/Auth/SignupPage/hooks/useCountdownTimer.ts
  src/pages/Auth/SignupPage/hooks/useFormatTime.ts
  src/pages/Auth/SignupPage/hooks/useStep.tsx
  src/pages/Auth/SignupPage/index.tsx
  src/pages/Store/StorePage/index.tsx
  src/static/auth.ts
  yarn.lock
Labels: 🐞 BugFix

#833 Bugsink sentry sdk setup
  .pnp.cjs
  .vscode/settings.json
  .yarn/cache/@sentry-browser-npm-9.14.0-0e2464dc6d-9392d17352.zip
  .yarn/cache/@sentry-core-npm-9.14.0-6df7ce92b3-7fc4f48236.zip
  .yarn/cache/@sentry-internal-browser-utils-npm-9.14.0-cb7c00e1d8-7fafbea6f1.zip
  .yarn/cache/@sentry-internal-feedback-npm-9.14.0-2cf0ca7c6d-f8ea2753d6.zip
  .yarn/cache/@sentry-internal-replay-canvas-npm-9.14.0-2a39a7c942-37dd3c3a2b.zip
  .yarn/cache/@sentry-internal-replay-npm-9.14.0-d6681f4f5f-bfded05a5b.zip
  package.json
  src/main.tsx
  yarn.lock
Labels: ⚙ Setting, 🕸️ platform

#824 [유저] 모바일 로그인 UI 변경
  src/assets/svg/Login/magnifying-glass.svg
  src/assets/svg/face-icon.svg
  src/assets/svg/lock-icon.svg
  src/pages/Auth/AuthPage/Auth.module.scss
  src/pages/Auth/AuthPage/index.tsx
  src/pages/Auth/LoginPage/LoginPage.module.scss
  src/pages/Auth/LoginPage/components/AdditionalLink/AdditionalLink.module.scss
  src/pages/Auth/LoginPage/components/AdditionalLink/index.tsx
  src/pages/Auth/LoginPage/components/Footer/Footer.module.scss
  src/pages/Auth/LoginPage/components/Footer/index.tsx
  src/pages/Auth/LoginPage/components/LoginForm/LoginForm.module.scss
  src/pages/Auth/LoginPage/components/LoginForm/index.tsx
  src/pages/Auth/LoginPage/hooks/useLogin.ts
  src/pages/Auth/LoginPage/index.tsx
  src/pages/Auth/SignupPage/hooks/useStep.tsx
  src/static/auth.ts
Labels: 🖌 UI, 👤 User
