Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2025-05, with the labels that each got.

#836 [플랫폼] 메타 헬멧 제거
  .pnp.cjs
  .yarn/cache/@types-react-helmet-npm-6.1.11-6d6a281744-e329d8ad82.zip
  .yarn/cache/react-fast-compare-npm-3.2.2-45b585a872-2071415b4f.zip
  .yarn/cache/react-helmet-npm-6.1.0-20fd5447ff-a4998479da.zip
  .yarn/cache/react-side-effect-npm-2.1.2-c18e5fd8bd-c5eb1f42b4.zip
  package.json
  src/App.tsx
  src/components/layout/MetaHelmet/index.tsx
  yarn.lock
Labels: 🔨 Refactor, 🕸️ platform

#834 [유저] 회원가입 중 새로고침 시 첫 step으로 돌아가는 에러 수정
  src/App.tsx
  src/components/layout/Header/PCHeader/index.tsx
  src/pages/Auth/LoginPage/components/AdditionalLink/index.tsx
  src/pages/Auth/LoginPage/components/LoginForm/index.tsx
  src/pages/Auth/SignupPage/hooks/useStep.tsx
  src/pages/Auth/SignupPage/index.tsx
  src/static/routes.ts
Labels: 🐞 BugFix, 👤 User

#840 [hotfix, 주변상점] 빈 문자열, 공백 입력 시 api 미호출
  src/pages/Store/StorePage/components/SearchBarModal/index.tsx
Labels: 🐞 BugFix, 💼 Business

#852 [유저] 회원가입 UI 에러 수정
  src/pages/Auth/AuthPage/Auth.module.scss
  src/pages/Auth/SignupPage/SignupPage.module.scss
  src/pages/Auth/SignupPage/Steps/MobileVerificationStep/MobileVerification.module.scss
  src/pages/Auth/SignupPage/Steps/MobileVerificationStep/index.tsx
  src/pages/Auth/SignupPage/Steps/Terms/Terms.module.scss
  src/pages/Auth/SignupPage/Steps/VerificationStep/index.tsx
  src/pages/Auth/SignupPage/components/CustomInput/CustomInput.module.scss
  src/static/routes.ts
Labels: 🐞 BugFix, ❗QA issue

#864 [캠퍼스] 동아리 목록 화면 구현
  src/api/club/APIDetail.ts
  src/api/club/entity.ts
  src/api/club/index.ts
  src/pages/Club/ClubListPage/ClubListPage.module.scss
  src/pages/Club/ClubListPage/index.tsx
  src/pages/Club/hooks/useClubCategories.ts
  src/pages/Club/hooks/useClubList.ts
  src/pages/Club/hooks/useHotClub.ts
  src/pages/IndexPage/IndexPage.module.scss
  src/pages/IndexPage/components/IndexClub/index.tsx
  src/static/routes.ts
Labels: ✨ Feature, 🎓 Campus

#868 [캠퍼스] 버그 수정
  .pnp.cjs
  .yarn/cache/@types-react-helmet-npm-6.1.11-6d6a281744-e329d8ad82.zip
  .yarn/cache/react-fast-compare-npm-3.2.2-45b585a872-2071415b4f.zip
  .yarn/cache/react-helmet-npm-6.1.0-20fd5447ff-a4998479da.zip
  .yarn/cache/react-side-effect-npm-2.1.2-c18e5fd8bd-c5eb1f42b4.zip
  package.json
  src/App.tsx
  src/components/layout/Header/PCHeader/index.tsx
  src/components/layout/MetaHelmet/index.tsx
  src/pages/Bus/BusCoursePage/components/Timetable/index.tsx
  yarn.lock
Labels: 🐞 BugFix, 🎓 Campus
