Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2025-03, with the labels that each got.

#708 [커스텀시간표] 요일 선택 이슈 해결
  src/pages/TimetablePage/components/CustomLecture/index.tsx
Labels: 🐞 BugFix, 👤 User

#710 [hotfix, 유저] 닉네임 중복확인 조건 추가
  src/pages/Articles/components/ArticleContent/ArticleContent.module.scss
  src/pages/Auth/SignupPage/hooks/useNicknameDuplicateCheck.ts
Labels: 🐞 BugFix, 👤 User

#712 [유저] 회원가입 시 성별 선택값으로
  src/pages/Auth/SignupPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#718 [졸업학점계산기] 1차 QA 수정
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/CreditChart.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
  src/pages/GraduationCalculatorPage/components/GraduationCalculatorAuthModal/index.tsx
  src/pages/GraduationCalculatorPage/components/StudentForm/StudentForm.module.scss
  src/pages/GraduationCalculatorPage/hooks/useAgreeGraduationCreidts.ts
  src/pages/GraduationCalculatorPage/hooks/useCalculateCredits.ts
  src/pages/GraduationCalculatorPage/hooks/useUpdateAcademicInfo.ts
  src/pages/GraduationCalculatorPage/index.tsx
  src/pages/TimetablePage/hooks/useDeleteSemester.ts
  src/pages/TimetablePage/hooks/useDeleteTimetableLecture.ts
  src/pages/TimetablePage/hooks/useEditTimetableLectureRegular.ts
  src/pages/TimetablePage/hooks/useGetMultiMajorLecture.ts
Labels: ❗QA issue, 👤 User

#722 [유저] 정보 수정 시 성별 미선택하면 "null"로 요청값 보내는 이슈 해결
  src/pages/Auth/ModifyInfoPage/index.tsx
Labels: 🐞 BugFix, 👤 User

#723 [졸업학점계산기] 2차 qa 이슈 수정
  src/api/auth/APIDetail.ts
  src/api/auth/entity.ts
  src/api/auth/index.ts
  src/api/graduationCalculator/entity.ts
  src/pages/GraduationCalculatorPage/CalculatorHelpModal/CalculatorHelpModal.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/CreditChart.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
  src/pages/GraduationCalculatorPage/components/ExcelUploader/ExcelUploader.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/GraduationCalculatorPage/components/StudentForm/StudentForm.module.scss
  src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
  src/pages/GraduationCalculatorPage/hooks/useUpdateAcademicInfo.ts
  src/pages/TimetablePage/components/Curriculum/Curriculum.module.scss
  src/pages/TimetablePage/hooks/useAllMyLectures.ts
  src/utils/hooks/state/useUserAcademicInfo.ts
Labels: ❗QA issue, 👤 User

#725 [졸업학점계산기] 서브 드롭다운 추가 및 2차 QA 반영
  src/api/timetable/entity.ts
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/CourseTypeList.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/GeneralCourseListModal.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/TimetablePage/hooks/useTimetableMutation.ts
Labels: ❗QA issue, 👤 User

#745 [졸업학점계산기] 2차 QA 이슈 최종 해결
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/CreditChart.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/SemesterLectureListModal.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/GeneralCourseListModal.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
  src/pages/GraduationCalculatorPage/index.tsx
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
  src/pages/TimetablePage/components/SemesterList/index.tsx
  src/pages/TimetablePage/hooks/useTotalGrades.ts
Labels: ❗QA issue, 👤 User

#747 [졸업학점계산기] 마지막 QA 이슈 해결
  src/components/common/Toast/TimetableToast/TimetableToast.module.scss
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
  src/pages/GraduationCalculatorPage/components/ExcelUploader/ExcelUploader.module.scss
  src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
  src/pages/GraduationCalculatorPage/index.tsx
  src/pages/TimetablePage/hooks/useAllMyLectures.ts
  src/pages/TimetablePage/hooks/useTotalGrades.ts
Labels: ❗QA issue, 👤 User

#749 [hotfix] 웹 문의하기 버튼 추가
  src/components/common/Footer/Footer.module.scss
  src/components/common/Footer/index.tsx
Labels: 🖌 UI

#754 [비지니스] 주변상점 메뉴 카테고리 변경 수정
  src/pages/Store/StoreDetailPage/components/MenuTable/MenuTable.module.scss
  src/pages/Store/StoreDetailPage/components/MenuTable/index.tsx
Labels: ❗QA issue, 💼 Business

#759 [hotfix] 모바일 시간표 학기 드롭다운 버튼 배경색 active 에러
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
Labels: ❗QA issue, 👤 User

#762 [캠퍼스] 모바일 공지사항 QA 수정
  src/api/articles/APIDetail.ts
  src/pages/Articles/LostItemChatPage/LostItemChatPage.module.scss
  src/pages/Articles/LostItemChatPage/index.tsx
  src/pages/Articles/LostItemDetailPage/index.tsx
  src/pages/Articles/LostItemWritePage/components/LostItemForm/LostItemForm.module.scss
  src/pages/Articles/LostItemWritePage/components/LostItemForm/index.tsx
  src/pages/Articles/hooks/usePostLostItemArticles.ts
  src/pages/Articles/hooks/useSingleLostItemArticle.ts
Labels: ❗QA issue, 🎓 Campus

#773 [캠퍼스] 공지사항 핫픽스
  src/App.tsx
  src/pages/Articles/LostItemDetailPage/components/Checkbox/Checkbox.module.scss
  src/pages/Articles/LostItemDetailPage/components/Checkbox/index.tsx
  src/pages/Articles/LostItemDetailPage/components/ReportForm/ReportForm.module.scss
  src/pages/Articles/LostItemDetailPage/components/ReportForm/index.tsx
  src/pages/Articles/LostItemDetailPage/components/ReportModal/ReportModal.module.scss
  src/pages/Articles/LostItemDetailPage/components/ReportModal/index.tsx
  src/pages/Articles/LostItemDetailPage/index.tsx
  src/pages/Articles/ReportPage/ReportPage.module.scss
  src/pages/Articles/ReportPage/index.tsx
  src/pages/Articles/hooks/useReportLostItemArticle.ts
  src/static/routes.ts
Labels: 🐞 BugFix, 🎓 Campus

#788 [캠퍼스] 배너 UI 생성
  .github/workflows/reviewer.json
  src/components/layout/Footer/index.tsx
  src/components/layout/Header/MobileHeader/Panel/index.tsx
  src/components/layout/Header/MobileHeader/index.tsx
  src/components/layout/Header/PCHeader/index.tsx
  src/components/modal/LoginRequiredModal/index.tsx
  src/lib/gtag.ts
  src/pages/Articles/components/HotArticle/index.tsx
  src/pages/Articles/hooks/useArticlesLogger.ts
  src/pages/Articles/hooks/useChatLogger.ts
  src/pages/Auth/LoginPage/index.tsx
  src/pages/Auth/SignupPage/index.tsx
  src/pages/Bus/BusCoursePage/components/BusTimetable/index.tsx
  src/pages/Bus/BusCoursePage/components/BusTimetableDetail/index.tsx
  src/pages/Bus/BusCoursePage/components/Timetable/index.tsx
  src/pages/Bus/components/BusNotice/index.tsx
  src/pages/Bus/hooks/useBusLogger.ts
  src/pages/Cafeteria/MobileCafeteriaPage/components/MobileDiningBlocks/index.tsx
  src/pages/Cafeteria/MobileCafeteriaPage/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/components/PCDiningBlocks/index.tsx
  src/pages/Cafeteria/PCCafeteriaPage/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/DeleteLectureModal/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/GraduationCalculatorPage/components/GraduationCalculatorAuthModal/index.tsx
  src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
  src/pages/GraduationCalculatorPage/hooks/useExcelUpload.ts
  src/pages/GraduationCalculatorPage/index.tsx
  src/pages/IndexPage/components/IndexArticles/index.tsx
  src/pages/IndexPage/components/IndexBus/index.tsx
  src/pages/IndexPage/components/IndexCafeteria/index.tsx
  src/pages/IndexPage/components/IndexStore/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/Store/StoreBenefitPage/index.tsx
  src/pages/Store/StoreDetailPage/components/Review/components/DeleteModal/DeleteModal.tsx
  src/pages/Store/StoreDetailPage/components/Review/components/ReviewButton/index.tsx
  src/pages/Store/StoreDetailPage/components/Review/components/ReviewReporting/index.tsx
  src/pages/Store/StoreDetailPage/components/Review/components/SelectButton/SelectButton.tsx
  src/pages/Store/StoreDetailPage/index.tsx
  src/pages/Store/StorePage/components/DesktopStoreList/index.tsx
  src/pages/Store/StorePage/components/EventCarousel/index.tsx
  src/pages/Store/StorePage/components/MobileStoreList/index.tsx
  src/pages/Store/StorePage/components/SearchBar/index.tsx
  src/pages/Store/StorePage/components/SearchBarModal/index.tsx
  src/pages/Store/StorePage/index.tsx
  src/pages/Store/StoreReviewPage/ReviewForm/ReviewForm.tsx
  src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/MainTimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/components/Curriculum/index.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/MainTimetable/index.tsx
  src/pages/TimetablePage/components/SemesterList/index.tsx
  src/utils/hooks/analytics/useLogger.ts
Labels: 🖌 UI, 🎓 Campus

#792 [캠퍼스] 배너 기능 추가
  src/api/banner/APIDetail.ts
  src/api/banner/entity.ts
  src/api/banner/index.ts
  src/api/index.ts
  src/components/ui/Banner/Banner.module.scss
  src/components/ui/Banner/hooks/useBannerCategories.ts
  src/components/ui/Banner/hooks/useBanners.ts
  src/components/ui/Banner/index.tsx
  src/pages/IndexPage/index.tsx
Labels: ✨ Feature, 🎓 Campus

#796 [캠퍼스] 로깅 추가 및 추가 기능 수정
  src/api/banner/entity.ts
  src/assets/svg/previous-arrow-icon.svg
  src/components/ui/Banner/Banner.module.scss
  src/components/ui/Banner/hooks/useBanners.ts
  src/components/ui/Banner/index.tsx
  src/pages/IndexPage/index.tsx
  src/utils/hooks/analytics/useLogger.ts
Labels: 🐞 BugFix, 🎓 Campus
