Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2025-09, with the labels that each got.

#982 [hotfix] 학기 변경에 따른 버스 시간표 기간 변경
  src/pages/Bus/BusCoursePage/components/Timetable/index.tsx
  src/pages/Bus/BusRoutePage/components/TimeDetail/TimeDetailMobile/index.tsx
  src/pages/Bus/BusRoutePage/components/TimeDetail/TimeDetailPC/index.tsx
  src/pages/Bus/BusRoutePage/hooks/useSemester.ts
Labels: 🔨 Refactor, 🎓 Campus

#987 [로그인] 로그인 과정 유효성 검증 오류 수정
  src/pages/Auth/LoginPage/hooks/useLogin.ts
Labels: 🐞 BugFix

#989 [hotfix] 버스 페이지에서 메인 화면 이동 시 흰 화면 렌더링
  src/pages/Bus/BusRoutePage/hooks/useCoopSemester.ts
Labels: 🐞 BugFix

#998 [식단과 식당] A/B테스트용 로깅버튼 추가
  src/components/IndexComponents/IndexCafeteria/index.tsx
  src/components/cafeteria/MobileCafeteriaPage/MobileCafeteriaPage.module.scss
  src/components/cafeteria/MobileCafeteriaPage/index.tsx
  src/components/cafeteria/PCCafeteriaPage/PCCafeteriaPage.module.scss
  src/components/cafeteria/PCCafeteriaPage/index.tsx
  src/utils/hooks/analytics/useSessionLogger.ts
Labels: ✅ Test

#1000 [chore] start:serve 스크립트 추가
  package.json
Labels: ⚙ Setting
