Repository BCSDLab/KOIN_WEB_RECODE, pull requests merged in 2025-02, with the labels that each got.

#646 [hotfix, 시간표] 시간표 페이지 뒤로가기 문제
  src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/MainTimetablePage/index.tsx
Labels: 🐞 BugFix, 👤 User

#651 [졸업학점계산기] 강의 테이블 및 교양 영역 컴포넌트 UI 생성
  src/assets/svg/ellipse-icon.svg
  src/pages/GraduationCalculatorPage/CalculatorHelpModal/CalculatorHelpModal.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/ExcelUploader/ExcelUploader.module.scss
  src/pages/GraduationCalculatorPage/components/ExcelUploader/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/GraduationCalculatorPage/components/LectureTable/LectureTable.module.scss
  src/pages/GraduationCalculatorPage/components/LectureTable/index.tsx
  src/pages/GraduationCalculatorPage/index.tsx
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
  src/pages/TimetablePage/components/SemesterList/index.tsx
Labels: ✨ Feature

#655 [캠퍼스] 분실물 쪽지 기능 구현
  .pnp.cjs
  .yarn/cache/@stomp-stompjs-npm-7.0.0-c66e011389-94618b5a39.zip
  package.json
  src/App.tsx
  src/api/articles/APIDetail.ts
  src/api/articles/entity.ts
  src/api/articles/index.ts
  src/assets/svg/Articles/block.svg
  src/assets/svg/Articles/chat.svg
  src/assets/svg/Articles/default-photo.svg
  src/assets/svg/Articles/person.svg
  src/assets/svg/Articles/send.svg
  src/pages/Articles/LostItemChatPage/LostItemChatPage.module.scss
  src/pages/Articles/LostItemChatPage/components/DeleteModal/DeleteModal.module.scss
  src/pages/Articles/LostItemChatPage/components/DeleteModal/hooks/useBlockLostItemChatroom.ts
  src/pages/Articles/LostItemChatPage/components/DeleteModal/index.tsx
  src/pages/Articles/LostItemChatPage/hooks/useChatroomQuery.ts
  src/pages/Articles/LostItemChatPage/index.tsx
  src/pages/Articles/LostItemChatPage/utils/date.ts
  src/pages/Articles/LostItemDetailPage/LostItemDetailPage.module.scss
  src/pages/Articles/LostItemDetailPage/hooks/usePostLostItemChatroom.ts
  src/pages/Articles/LostItemDetailPage/index.tsx
  src/pages/Articles/components/ArticleContent/ArticleContent.module.scss
  src/static/category.ts
  src/static/routes.ts
  vite.config.ts
  yarn.lock
Labels: ✨ Feature, 🎓 Campus

#656 [시간표] 커스텀 시간표 페이지 리팩터링
  src/api/timetable/APIDetail.ts
  src/components/TimetablePage/LectureTable/index.tsx
  src/components/TimetablePage/Listbox/index.tsx
  src/pages/IndexPage/components/IndexTimetable/index.tsx
  src/pages/TimetablePage/MainTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/MainTimetablePage/MobilePage/index.tsx
  src/pages/TimetablePage/MainTimetablePage/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/DefaultPage/index.tsx
  src/pages/TimetablePage/ModifyTimetablePage/index.tsx
  src/pages/TimetablePage/components/CustomLecture/index.tsx
  src/pages/TimetablePage/components/LectureList/index.tsx
  src/pages/TimetablePage/components/MainTimetable/DownloadTimetableModal/index.tsx
  src/pages/TimetablePage/components/MainTimetable/index.tsx
  src/pages/TimetablePage/components/Timetable/Timetable.module.scss
  src/pages/TimetablePage/components/Timetable/index.tsx
  src/pages/TimetablePage/hooks/useEditTimetableLectureCustom.ts
  src/pages/TimetablePage/hooks/useEditTimetableLectureRegular.ts
  src/pages/TimetablePage/hooks/useMyLectures.ts
  src/pages/TimetablePage/hooks/useRollbackLecture.ts
  src/pages/TimetablePage/hooks/useRollbackTimetableFrame.ts
  src/pages/TimetablePage/hooks/useTimetableMutation.ts
  src/static/timetable.ts
  src/utils/zustand/myCustomTempLecture.ts
Labels: 🔨 Refactor, 👤 User

#665 [졸업학점계산기] 학번, 학과, 전공 입력 폼 생성
  src/api/auth/entity.ts
  src/api/dept/APIDetail.ts
  src/api/dept/entity.ts
  src/api/dept/index.ts
  src/api/graduationCalculator/APIDetail.ts
  src/api/graduationCalculator/entity.ts
  src/api/graduationCalculator/index.ts
  src/api/index.ts
  src/pages/Auth/ModifyInfoPage/index.tsx
  src/pages/Auth/SignupPage/hooks/useDeptList.ts
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/StudentForm/StudentForm.module.scss
  src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
  src/pages/GraduationCalculatorPage/hooks/useDepartmentMajorList.ts
  src/pages/GraduationCalculatorPage/hooks/useRemainingCredits.ts
  src/utils/hooks/auth/useUserInfoUpdate.ts
Labels: ✨ Feature, 👤 User

#666 [졸업학점계산기] 교양 과목 목록 모달 생성
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/GeneralCourseListModal.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/GraduationCalculatorPage/index.tsx
Labels: 🖌 UI, 👤 User

#671 [졸업학점계산기] 이수구분별 학점 그래프 UI 구현
  .pnp.cjs
  .yarn/cache/@esbuild-darwin-arm64-npm-0.21.5-62349c1520-8.zip
  .yarn/cache/@esbuild-win32-x64-npm-0.21.5-eddc2b5ad6-8.zip
  .yarn/cache/@rollup-rollup-darwin-arm64-npm-4.22.4-1dd8e67109-8.zip
  .yarn/cache/@rollup-rollup-win32-x64-msvc-npm-4.22.4-f32030f087-8.zip
  .yarn/cache/framer-motion-npm-12.4.4-23a597f2e4-2e6de97658.zip
  .yarn/cache/motion-dom-npm-12.4.4-d68ef9ec84-1ae17d9f5c.zip
  .yarn/cache/motion-utils-npm-12.0.0-452fbe000e-0b6ad4e102.zip
  .yarn/cache/tslib-npm-2.8.1-66590b21b8-e4aba30e63.zip
  package.json
  src/pages/GraduationCalculatorPage/components/CreditChart/CreditChart.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss
  src/pages/GraduationCalculatorPage/index.tsx
  yarn.lock
Labels: 🖌 UI, 👤 User

#675 [졸업학점계산기] 이수구분 드롭다운 구현
  src/api/timetable/entity.ts
  src/assets/svg/chervron-up-grey.svg
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/CourseTypeList.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/ExcelUploader/ExcelUploader.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/GeneralCourseListModal.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/index.tsx
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
  src/pages/TimetablePage/components/SemesterList/index.tsx
  src/pages/TimetablePage/hooks/useTimetableMutation.ts
Labels: ✨ Feature, 👤 User

#680 [졸업학점계산기] 학적 정보 수정 추가
  src/api/auth/APIDetail.ts
  src/api/auth/entity.ts
  src/api/auth/index.ts
  src/api/graduationCalculator/index.ts
  src/pages/GraduationCalculatorPage/components/StudentForm/index.tsx
  src/pages/GraduationCalculatorPage/hooks/useAgreeGraduationCreidts.ts
  src/pages/GraduationCalculatorPage/hooks/useUpdateAcademicInfo.ts
  src/pages/GraduationCalculatorPage/index.tsx
Labels: ✨ Feature, 👤 User

#681 [졸업학점계산기] 이수구분별 학점 그래프 api 연동
  src/api/graduationCalculator/APIDetail.ts
  src/api/graduationCalculator/entity.ts
  src/api/graduationCalculator/index.ts
  src/pages/GraduationCalculatorPage/CalculatorHelpModal/CalculatorHelpModal.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/GeneralCourseListModal.module.scss
  src/pages/GraduationCalculatorPage/hooks/useAgreeGraduationCreidts.ts
  src/pages/GraduationCalculatorPage/hooks/useCalculateCredits.ts
  src/pages/GraduationCalculatorPage/hooks/useExcelUpload.ts
  src/pages/GraduationCalculatorPage/hooks/useUpdateAcademicInfo.ts
  src/pages/TimetablePage/hooks/useEditTimetableLectureRegular.ts
Labels: ✨ Feature, 👤 User

#683 [졸업학점계산기] 로그인 유도 모달 구현
  src/pages/GraduationCalculatorPage/components/GraduationCalculatorAuthModal/GraduationCalculatorAuthModal.module.scss
  src/pages/GraduationCalculatorPage/components/GraduationCalculatorAuthModal/index.tsx
  src/pages/GraduationCalculatorPage/index.tsx
Labels: ✨ Feature

#688 [졸업학점계산기] 커리큘럼 드롭다운 메뉴 너비 수정
  src/pages/GraduationCalculatorPage/GraduationCalculatorPage.module.scss
  src/pages/GraduationCalculatorPage/index.tsx
  src/pages/TimetablePage/components/Curriculum/Curriculum.module.scss
  src/pages/TimetablePage/components/Curriculum/index.tsx
Labels: 🖌 UI, 👤 User

#686 [졸업학점계산기] 교양 컴포넌트 api 연결
  src/api/graduationCalculator/APIDetail.ts
  src/api/graduationCalculator/entity.ts
  src/api/graduationCalculator/index.ts
  src/assets/svg/ellipse-icon-green.svg
  src/assets/svg/ellipse-icon-red.svg
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CreditChart/CreditChart.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourse.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/GraduationCalculatorPage/hooks/useCourseType.ts
  src/pages/GraduationCalculatorPage/hooks/useGeneralEducation.ts
  src/pages/GraduationCalculatorPage/index.tsx
  src/pages/TimetablePage/components/SemesterList/SemesterList.module.scss
  src/pages/TimetablePage/components/SemesterList/index.tsx
Labels: ✨ Feature, 👤 User

#694 [커스텀시간표] 드롭다운 메뉴 위로 올라가는 이슈 수정
  src/pages/TimetablePage/components/CustomLecture/index.tsx
Labels: 🐞 BugFix, 👤 User

#695 [졸업학점계산기] 강의 삭제 모달 생성 및 이수 구분 범위 넘어가는 문제 해결
  src/api/graduationCalculator/APIDetail.ts
  src/api/graduationCalculator/entity.ts
  src/components/common/Toast/TimetableToast/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/CourseTypeList.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/CourseTypeList/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/DeleteLectureModal/DeleteLectureModal.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/DeleteLectureModal/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/SemesterCourseTable.module.scss
  src/pages/GraduationCalculatorPage/components/CourseTable/SemesterCourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/CourseTable/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/GeneralCourseListModal.module.scss
  src/pages/GraduationCalculatorPage/components/GeneralCourse/GeneralCourseListModal/index.tsx
  src/pages/GraduationCalculatorPage/components/GeneralCourse/index.tsx
  src/pages/TimetablePage/hooks/useTimetableMutation.ts
Labels: ✨ Feature, 👤 User

#703 [졸업학점계산기] 학기 강의 개설 목록 모달 내 드롭다운을 Selector로 리팩터링
  src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/SemesterLectureListModal.module.scss
  src/pages/GraduationCalculatorPage/components/CreditChart/SemesterLectureListModal/index.tsx
  src/pages/TimetablePage/components/LectureList/DeptListbox.tsx
Labels: ✨ Feature, 👤 User
